### PR TITLE
OF-1474_hazelcast_rest_api_create_room_npe

### PR DESCRIPTION
**Pull request by dbh**
Upon External Serialization, do a null check on modificationDate. It is possible that the modificationDate is null, if the room was just created through REST API and Hazelcast enabled with more than 1 node in the cluster.  That results in an NPE, partial room creation, and failure in communicating the room updated event via hazelcast.

If modification date is null, send the creationDate value instead for the hazelcast room updated event

see https://discourse.igniterealtime.org/t/openfire-hazelcast-clustering-rest-api-room-creation-npe-when-no-modificaitondate-sent/80619/2

### CODE REVIEW

**Comment by GregDThomas** [comment]
This does mean the same room on different nodes of the cluster will have different modificationDates, which seems wrong. Instead, could you you do something like ...

`ExternalizableUtil.getInstance().writeLong(out, modificationDate == null ? null : modificationDate.getTime());`

and

`Long modificationDateLong = ExternalizableUtil.getInstance().readLong(in);`
`modificationDate = modificationDateLong == null ? null : new Date(modificationDateLong);`

**Comment by dbh** [comment]
I'll play with this a bit and get back to you

**Comment by dbh** [comment]
This appears to now long be needed. Greg Thomas pushed a commit for this particular issue.

**Comment by GregDThomas** [comment]
(Yes, this PR still needs to be merged, though I did tweak it to ensure a null modificationDate was preserved)

**Pull request merged**
