### PR TITLE
OF-1571: Ensure RECVd messages are logged

### PR DESCRIPTION
**Pull request by GregDThomas**
NB. Also removed logged of empty messages, and made the Interpreted logger be consistent with the name of `RECV`d messages.

### CODE REVIEW

**Comment by akrherz** [comment]
@GregDThomas Does this mean white-space pings would not be logged?

**Comment by GregDThomas** [comment]
Ah, is that what all those blank lines are for? Yes, it would. Let me know if that's an issue ...

**Comment by akrherz** [comment]
@GregDThomas some XMPP clients do not do IQ-ping, so they do whitespace pings.  I am unsure if it is important to check those in the generated logs or not.

**Comment by guusdk** [comment]
Maybe make it configurable?

**Comment by GregDThomas** [comment]
OK, done :)

**Comment by GregDThomas** [comment]
@akrherz - this bumped the Debugger plugin to 1.7.1 - any chance you could update the list of plugins at https://www.igniterealtime.org/projects/openfire/plugins.jsp with it? Thanks

**Comment by akrherz** [comment]
@GregDThomas done.  FYI, the size of the plugin went from 15,855 bytes to 1,675,349 bytes.

**Comment by GregDThomas** [comment]
Thanks Daryl. The size increase is because of some extra dependencies needed for pre-Openfire 4.3 servers, it will shrink again when https://issues.igniterealtime.org/browse/OF-1570 is implemented.

**Pull request merged**
