### PR TITLE
Documentation: add minimal working examples

### PR DESCRIPTION
**Pull request by guusdk**
This PR adds documentation for various client libraries that show a minimum working example of how to use that client with Openfire.

### CODE REVIEW

**Comment by guusdk** [comment]
Preview link (will probably break over time): https://htmlpreview.github.io/?https://github.com/igniterealtime/Openfire/blob/50bf2fbdaa1e0c9f14423437aec014b99b4fb5cd/documentation/client-minimal-working-example-smack.html

**Comment by deleolajide** [comment]
I should do one for sparkweb.js when I finish implementing all the web components. I will submit a PR when that happens

**Comment by guusdk** [comment]
Added more pages, for:
- Mellium
- XmppDotNet

**Comment by guusdk** [comment]
Added:
- Twisted (Words)

**Comment by guusdk** [comment]
Added:
- moxxmpp

**Pull request merged**
