### PR TITLE
OF-976 Language is not properly set in HttpSession

### PR DESCRIPTION
**Pull request by sco0ter**

### CODE REVIEW

**Comment by dwd** [comment]
I *think* this is effectively a no-op; the XML namespace is bound to the prefix "xml" by standards action and cannot be rebound. I'm happy for this to go in, though:

+1

(Just not sure it makes any difference).

**Comment by sco0ter** [comment]
´rootNode.attributeValue("xml:lang")´ returned null, even if this attribute was set.

**Comment by dwd** [comment]
Ah, so I'd misunderstood. Thanks for the clarification.

**Comment by tevans** [comment]
+1

**Pull request merged**
