### PR TITLE
Denote Openfire 4.3.0 Beta Release

### PR DESCRIPTION
**Pull request by akrherz**

### CODE REVIEW

**Comment by akrherz** [comment]
Well, Travis is green, who wants to be a hero and merge this?

**Comment by deleolajide** [comment]
I would like [my PR](https://github.com/igniterealtime/Openfire/pull/1231) to be included in this please

**Comment by guusdk** [comment]
I like living on the edge.

**Comment by akrherz** [comment]
@deleolajide your PR is plugin-only, so we can async release it.

**Comment by deleolajide** [comment]
ok

**Pull request merged**
