### PR TITLE
OF-821: Prevent duplicates for MUC item query

### PR DESCRIPTION
**Pull request by tevans**
Corrects issue with multiple JIDs sharing a nickname (masquerading)

### CODE REVIEW

**Comment by sco0ter** [comment]
I don't know, if it's a good idea to return null from the toString() method. Maybe better return super.toString()?

Otherwise +1

**Comment by tevans** [comment]
That's a fair point ... actually upon closer inspection it seems element can't actually be null (under normal circumstances), since there is no default constructor. I'll just drop the null check instead.

**Comment by dwd** [comment]
This partially solves the bug by removing/suppressing duplicate disco#item entries, but it leaves the number of occupants reported by Disco as including any nick shares. I'm happy that this is useful, but I'm just checking how easy it'd be to fix the count reported, too.

**Comment by dwd** [comment]
It's not clear whether getOccupantsCount() would be safe to update, so I'm going to leave this for another time.

**Pull request merged**
