### PR TITLE
[Security issue]Keystore passwords are not encrypted in the ofProperty table

### PR DESCRIPTION
**Pull request by promiselaoliu**
Save encrypted passwords to DB

### CODE REVIEW

**Comment by promiselaoliu** [comment]
continuous-integration/travis-ci/pr — The Travis CI build failed
Why? 
Integration test is dependent on the plain text password?

**Comment by GregDThomas** [comment]
Most likely a more general CI issue. I've restarted it ...

**Comment by GregDThomas** [comment]
... but clearly something more substantial than that.

**Comment by GregDThomas** [comment]
I'm going to merge this; I can see no reason why the ITs are failing - and I know there have been improvements recently that may not have been picked up by this branch yet.

**Comment by guusdk** [comment]
Will this change play nice with existing installations?

**Comment by GregDThomas** [comment]
Yes; any existing property remains un-encrypted - only when the password is updated will the change take effect.

**Pull request merged**
