### PR TITLE
OF-2716: Fix Licences

### PR DESCRIPTION
**Pull request by Fishbowler**
Replaces #2367 (because I accidentally deleted the branch)

### CODE REVIEW

**Comment by Fishbowler** [comment]
Script moved to https://gist.github.com/Fishbowler/ed6a05c4e7b7ba539f814df3f54e5772
I wanted it in Ignite Realtime, but I can't see a way to create gists in organisations.

**Comment by Fishbowler** [comment]
I'm going to rewrite history to remove the script.

**Comment by Fishbowler** [comment]
Done, ready for merge

**Review by guusdk — APPROVED** [review]
I've skimmed over examples of the changes, with regards to years and legal entity references, which seems to be fine.

I've used (suboptimal) bash grepping to verify that all changes in this PR affect lines that are in comment, which turns out to be the case nearly everywhere (some JSP import statements got moved around too, which is fine):

```
git diff 68ecdf119e6f17e81f84bef84d5a2b2dcd2c0edf HEAD | grep "^[\+\-]" | grep -v "^---" | grep -v "^++" | grep -v -E '^[+-] \*' | grep -v "^[+-]  -"
```
That's all that I can think of to sensibly review this PR. Thanks for all of the effort that has gone into this, @Fishbowler !

**Review by akrherz — APPROVED** [review]

**Pull request merged**
