### PR TITLE
remove CRLF from *.{html,css,sql,xml,js,properties,jspf,java,jsp}

### PR DESCRIPTION
**Pull request by akrherz**
all done via the magic of dos2unix

### CODE REVIEW

**Comment by akrherz** [comment]
Files not hit by this
```
$ find . -not -type d -exec file "{}" ";" | grep CRLF
./build/installer/openfire.install4j: XML 1.0 document, ASCII text, with very long lines, with CRLF line terminators
./build/projects/Openfire.ipr: XML 1.0 document, ASCII text, with CRLF line terminators
./build/wildfireHome/embedded-db/wildfire.script: ASCII text, with very long lines, with CRLF line terminators
./src/bin/extra/embedded-db.rc: ASCII text, with CRLF line terminators
./src/bin/openfire-dev.bat: DOS batch file, ASCII text, with very long lines, with CRLF line terminators
./src/bin/openfire.bat: DOS batch file, ASCII text, with CRLF line terminators
./src/plugins/kraken/lib/patches/smack.sasl.patch: unified diff output, ASCII text, with CRLF, LF line terminators
./src/plugins/rayo/src/demo/confphone.mxml: XML 1.0 document, ASCII text, with CRLF line terminators
./src/plugins/rayo/src/demo/make_confphone.cmd: ASCII text, with CRLF line terminators
./src/plugins/inverse/classes/inverse/css/images/arrow.svg: ASCII text, with CRLF line terminators
./src/plugins/inverse/classes/inverse/css/images/bgbl.svg: HTML document, ASCII text, with CRLF line terminators
./src/plugins/inverse/classes/inverse/css/images/bgtr.svg: HTML document, ASCII text, with CRLF line terminators
./src/plugins/inverse/classes/inverse/css/images/dark-arrow.svg: ASCII text, with CRLF line terminators
./src/resources/jar/META-INF/mime.types: ASCII text, with CRLF line terminators
./src/test/throttletest/build/ThrottleTest.ipr: XML 1.0 document, ASCII text, with CRLF line terminators
./xmppserver/target/classes/META-INF/mime.types: ASCII text, with CRLF line terminators
```

**Comment by akrherz** [comment]
OK, gonna piggyback now a change to replace all tabs in those same files with four spaces

**Comment by akrherz** [comment]
So the last commit should be the only code change.  I assume it is necessary as the trailing line feed is now interpreted by the JSP compiler as the need to print an extra empty space?

**Comment by dwd** [comment]
I'm confused - why would adding a line feed at the end cause the return statement to be unneeded? And what's the harm in leaving them in?

**Pull request merged**
