### PR TITLE
OF-454 Reflect presence to originator

### PR DESCRIPTION
**Pull request by dwd**

### CODE REVIEW

**Comment by tevans** [comment]
Agree with @sco0ter here - I think you can instead remove the conditional statement that excludes the current session from the broadcast: `if (!originatingResource.equals(address)) { ... }`

Not as sure about the initial presence broadcast referred to at line 626 - seems like that takes a different path, although that code also mentions the same section of the RFC.

**Comment by sco0ter** [comment]
There are two very similar sections in RFC 6121: 4.2.2 and 4.4.2.
Openfire follows 4.2.2 (I think line 624 should actually refer to 4.2.2), but not 4.4.2.

Initial presence logic first traverses broadcastPresenceToOtherResources() and later sessionAvailable(), making the initial presence being reflected twice.

**Comment by dwd** [comment]
@tevans I can't remove the conditional because there's an early exit based around an option; so I need to do it in two steps - however, it looks like @sco0ter is again right, there's already reflection for initial presence.

**Comment by guusdk** [comment]
+1

**Comment by dwd** [comment]
Anyone else?

**Comment by sco0ter** [comment]
+1, squash if you want.

**Pull request merged**
