### PR TITLE
OF-2845: Countdown latch on connection close exception

### PR DESCRIPTION
**Pull request by guusdk**
This should prevent connections from having to wait for a 10-minute timeout when an exception occurs while trying to invoke the close listeners.

### CODE REVIEW

**Comment by akrherz** [comment]
I'm testing this and I think this TRACE log series shows improved interaction here

<details>

```
2024.07.08 17:41:03.542 ESC[30mTRACEESC[m [socket_c2s-thread-17]: org.jivesoftware.openfire.nio.NettyConnectionHandler - Netty XMPP handler added: /10.90.12.28:5222--/129.186.185.26:44700
2024.07.08 17:41:03.956 ESC[30mTRACEESC[m [socket_c2s-thread-17]: org.jivesoftware.openfire.nio.NettyConnectionHandler - Handler on /10.90.12.28:5222--/129.186.185.26:44700 received: <?xml v
ersion='1.0'?>
2024.07.08 17:41:03.956 ESC[30mTRACEESC[m [socket_c2s-thread-17]: org.jivesoftware.openfire.nio.NettyConnectionHandler - Handler on /10.90.12.28:5222--/129.186.185.26:44700 received: <stream
:stream from='scanner@censys.io' version='1.0' xml:lang='en' xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams'>
2024.07.08 17:41:03.957 ESC[30mTRACEESC[m [socket_c2s-thread-17]: org.jivesoftware.openfire.net.SASLAuthentication - Cannot support 'GSSAPI' as the 'sasl.gssapi.config' property has not been
 defined.
2024.07.08 17:41:03.957 ESC[30mTRACEESC[m [socket_c2s-thread-17]: org.jivesoftware.openfire.net.SASLAuthentication - Cannot support 'JIVE-SHAREDSECRET' as it has been disabled by configurati
on.
2024.07.08 17:41:03.959 ESC[30mTRACEESC[m [socket_c2s-thread-17]: org.jivesoftware.openfire.nio.NettyConnection - Sending: <?xml version="1.0" encoding="UTF-8"?><stream:stream xmlns:stream="
http://etherx.jabber.org/streams" xmlns="jabber:client" from="weather.im" id="9apfw6zl5t" xml:lang="en" version="1.0"><stream:features><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/><lim
its xmlns="urn:xmpp:stream-limits:0"><max-bytes>1048576</max-bytes><idle-seconds>360</idle-seconds></limits><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><
mechanism>ANONYMOUS</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>CRAM-MD5</mechanism></mechanisms><compression xmlns="http://jabber.org/features/compress"><method>zlib</method></c
ompression><ver xmlns="urn:xmpp:features:rosterver"/><c xmlns="http://jabber.org/protocol/caps" hash="sha-1" node="https://www.igniterealtime.org/projects/openfire/" ver="mW6O6ZU/CElPcCA9fRa
FqESjcqg="/><limits xmlns="urn:xmpp:stream-limits:0"><max-bytes>1048576</max-bytes><idle-seconds>360</idle-seconds></limits></stream:features>
2024.07.08 17:41:04.757 ESC[33mWARN ESC[m [socket_c2s-thread-17]: org.jivesoftware.openfire.nio.NettyXMPPDecoder - Error occurred while decoding XMPP stanza, closing connection: NettyConnect
ion{peer: /129.186.185.26:44700, state: OPEN, session: LocalClientSession{address=weather.im/119dd9de-e193-43ce-8bcf-a25c95f37f74, streamID=9apfw6zl5t, status=CONNECTED, isEncrypted=false, i
sDetached=false, serverName='weather.im', isInitialized=false, hasAuthToken=false, peer address='129.186.185.26', presence='
<presence type="unavailable"/>'}, Netty channel handler context name: NettyClientConnectionHandler#0}
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:?]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[?:?]
        at sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[?:?]
        at sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356) ~[?:?]
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255) ~[netty-buffer-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.108.Final.jar:4.1.108.Final]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2024.07.08 17:41:04.758 ESC[30mTRACEESC[m [socket_c2s-thread-17]: org.jivesoftware.openfire.nio.NettyConnection - Closing NettyConnection{peer: /129.186.185.26:44700, state: CLOSED, session:
 LocalClientSession{address=weather.im/119dd9de-e193-43ce-8bcf-a25c95f37f74, streamID=9apfw6zl5t, status=CONNECTED, isEncrypted=false, isDetached=false, serverName='weather.im', isInitialize
d=false, hasAuthToken=false, peer address='129.186.185.26', presence='
<presence type="unavailable"/>'}, Netty channel handler context name: NettyClientConnectionHandler#0} with optional error: 
<stream:error xmlns:stream="http://etherx.jabber.org/streams">
  <internal-server-error xmlns="urn:ietf:params:xml:ns:xmpp-streams"/>
  <text xmlns="urn:ietf:params:xml:ns:xmpp-streams">An error occurred in XMPP Decoder</text>
</stream:error>
2024.07.08 17:41:04.758 ESC[30mTRACEESC[m [socket_c2s-thread-17]: org.jivesoftware.openfire.nio.NettyConnection - Flushed any final bytes, closing connection.
2024.07.08 17:41:04.758 ESC[30mTRACEESC[m [socket_c2s-thread-17]: org.jivesoftware.openfire.nio.NettyConnection - Notifying close listeners.
2024.07.08 17:41:04.758 ESC[36mDEBUGESC[m [socket_c2s-thread-17]: org.jivesoftware.openfire.SessionManager - Closing session with address weather.im/119dd9de-e193-43ce-8bcf-a25c95f37f74 and streamID 9apfw6zl5t does not have SM enabled.
2024.07.08 17:41:04.758 ESC[30mTRACEESC[m [socket_c2s-thread-17]: org.jivesoftware.openfire.spi.RoutingTableImpl - hasClientRoute() invoked with a JID that's not a full JID: weather.im/119dd9de-e193-43ce-8bcf-a25c95f37f74
2024.07.08 17:41:04.758 ESC[36mDEBUGESC[m [socket_c2s-thread-17]: org.jivesoftware.openfire.spi.RoutingTableImpl - Removing client route weather.im/119dd9de-e193-43ce-8bcf-a25c95f37f74
2024.07.08 17:41:04.758 ESC[30mTRACEESC[m [socket_c2s-thread-17]: org.jivesoftware.openfire.spi.RoutingTableImpl - Removing client route weather.im/119dd9de-e193-43ce-8bcf-a25c95f37f74 from local routing table
2024.07.08 17:41:04.758 ESC[30mTRACEESC[m [socket_c2s-thread-17]: org.jivesoftware.openfire.spi.LocalRoutingTable - Remove local route '(null)' (for pair: '{ -> weather.im/119dd9de-e193-43ce-8bcf-a25c95f37f74}') not removed (was not present).
2024.07.08 17:41:04.758 ESC[30mTRACEESC[m [socket_c2s-thread-17]: org.jivesoftware.openfire.nio.NettyConnection - Finished closing connection.
2024.07.08 17:41:04.758 ESC[1;31mERRORESC[m [socket_c2s-thread-17]: org.jivesoftware.openfire.nio.NettyConnection - Problem during connection close or cleanup
java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:?]
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47) ~[?:?]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113) ~[?:?]
        at sun.nio.ch.IOUtil.write(IOUtil.java:58) ~[?:?]
        at sun.nio.ch.IOUtil.write(IOUtil.java:50) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:462) ~[?:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:415) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:359) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:935) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:921) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:907) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:939) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:957) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:982) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:950) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:1000) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at org.jivesoftware.openfire.nio.NettyConnection.close(NettyConnection.java:215) [xmppserver-4.8.2.jar:4.8.3-SNAPSHOT]
        at org.jivesoftware.openfire.nio.NettyXMPPDecoder.exceptionCaught(NettyXMPPDecoder.java:71) [xmppserver-4.8.2.jar:4.8.3-SNAPSHOT]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:317) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:325) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:125) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:177) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.108.Final.jar:4.1.108.Final]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2024.07.08 17:41:04.759 ESC[30mTRACEESC[m [socket_c2s-thread-17]: org.jivesoftware.openfire.nio.NettyConnectionHandler - Netty XMPP handler removed: /10.90.12.28:5222--/129.186.185.26:44700
```

</details>

**Comment by akrherz** [comment]
Note to self, I have yet to see `Unexpected packet tag` and I should denote the interaction when that happens before declaring victory.

**Comment by guusdk** [comment]
> I'm testing this and I think this TRACE log series shows improved interaction here

I'm not sure if this is the _same_ condition that we saw before. Before, I think that we have seen a client sending invalid data. This   now appears to be a client closing the connection (although I must admit that the exception that's logged suggests a parsing prolbem, which confuses me).

**Comment by akrherz** [comment]
And here's an `Unexpected packet tag` example :)

<details>

```
2024.07.09 00:46:38.699 ESC[33mWARN ESC[m [socket_c2s-thread-11]: org.jivesoftware.openfire.net.StanzaHandler - Unexpected packet tag (not message,iq,presence)<nessus/>. Closing session: LocalClientSession{address=weather.im/28d9682d-53a2-4eb2-95e9-2fe8c87138d7, streamID=7sqpt1vtbn, status=CONNECTED, isEncrypted=false, isDetached=false, serverName='weather.im', isInitialized=false, hasAuthToken=false, peer address='129.186.185.27', presence='
<presence type="unavailable"/>'}
2024.07.09 00:46:38.699 ESC[30mTRACEESC[m [socket_c2s-thread-11]: org.jivesoftware.openfire.nio.NettyConnection - Closing NettyConnection{peer: /129.186.185.27:51994, state: CLOSED, session: LocalClientSession{address=weather.im/28d9682d-53a2-4eb2-95e9-2fe8c87138d7, streamID=7sqpt1vtbn, status=CONNECTED, isEncrypted=false, isDetached=false, serverName='weather.im', isInitialized=false, hasAuthToken=false, peer address='129.186.185.27', presence='
<presence type="unavailable"/>'}, Netty channel handler context name: NettyClientConnectionHandler#0} with optional error: null
2024.07.09 00:46:38.699 ESC[1;31mERRORESC[m [socket_c2s-thread-11]: org.jivesoftware.openfire.nio.NettyConnection - Problem during connection close or cleanup
io.netty.util.concurrent.BlockingOperationException: DefaultChannelPromise@569d7e80(incomplete)
        at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:463) ~[netty-common-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.DefaultChannelPromise.checkDeadLock(DefaultChannelPromise.java:159) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:248) ~[netty-common-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:131) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:30) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:405) ~[netty-common-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:119) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:30) ~[netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at org.jivesoftware.openfire.nio.NettyConnection.close(NettyConnection.java:237) ~[xmppserver-4.8.2.jar:4.8.3-SNAPSHOT]
        at org.jivesoftware.openfire.Connection.close(Connection.java:177) ~[xmppserver-4.8.2.jar:4.8.3-SNAPSHOT]
        at java.util.Optional.ifPresent(Optional.java:183) [?:?]
        at org.jivesoftware.openfire.session.LocalSession.close(LocalSession.java:481) [xmppserver-4.8.2.jar:4.8.3-SNAPSHOT]
        at org.jivesoftware.openfire.net.StanzaHandler.process(StanzaHandler.java:339) [xmppserver-4.8.2.jar:4.8.3-SNAPSHOT]
        at org.jivesoftware.openfire.net.StanzaHandler.processStanza(StanzaHandler.java:222) [xmppserver-4.8.2.jar:4.8.3-SNAPSHOT]
        at org.jivesoftware.openfire.net.StanzaHandler.process(StanzaHandler.java:114) [xmppserver-4.8.2.jar:4.8.3-SNAPSHOT]
        at org.jivesoftware.openfire.nio.NettyConnectionHandler.channelRead0(NettyConnectionHandler.java:142) [xmppserver-4.8.2.jar:4.8.3-SNAPSHOT]
        at org.jivesoftware.openfire.nio.NettyConnectionHandler.channelRead0(NettyConnectionHandler.java:50) [xmppserver-4.8.2.jar:4.8.3-SNAPSHOT]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) [netty-codec-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) [netty-codec-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:289) [netty-handler-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:506) [netty-handler-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [netty-transport-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.108.Final.jar:4.1.108.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.108.Final.jar:4.1.108.Final]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2024.07.09 00:46:43.731 ESC[30mTRACEESC[m [socket_c2s-thread-11]: org.jivesoftware.openfire.nio.NettyConnectionHandler - Netty XMPP handler removed: /10.90.12.28:5222--/129.186.185.27:51994
```

**Comment by guusdk** [comment]
That seems to have logged the expected behavior. Were any threads blocked (for 10 minutes) on that latch?

**Comment by akrherz** [comment]
> That seems to have logged the expected behavior. Were any threads blocked (for 10 minutes) on that latch?

I don't believe so as thread `socket_c2s-thread-11` is logged doing other things within that time.

```
2024.07.09 00:48:16.217 ESC[30mTRACEESC[m [socket_c2s-thread-11]: org.jivesoftware.openfire.nio.NettyConnectionHandler - Handler on /10.90.12.28:5222--/129.186.185.27:53280 received: <?xml version="1.0"?>
```

I also have not found log entries for `Timed out waiting for close listeners to complete.`

**Pull request merged**
