### PR TITLE
Migrate Travis to Github Actions

### PR DESCRIPTION
**Pull request by Fishbowler**
There's some duplication already.
Between Bamboo, Travis and Github Actions, there's quite a bit.
Bamboo needs to stay for the installer generating, but we could drop from 3 CI systems to 2.

### CODE REVIEW

**Comment by Fishbowler** [comment]
All ported, except downstream plugin builds (which were broken anyway).
Captured in https://issues.igniterealtime.org/browse/OF-2090

**Comment by Fishbowler** [comment]
One last task. This needs secrets adding (https://github.com/igniterealtime/Openfire/settings/secrets) called IGNITE_REALTIME_MAVEN_USERNAME and IGNITE_REALTIME_MAVEN_PASSWORD for someone who knows them.

**Comment by akrherz** [comment]
Thanks so much, could the `README.md` badge be updated too?

**Comment by Fishbowler** [comment]
@akrherz Readme updated 👍

**Comment by guusdk** [comment]
> One last task. This needs secrets adding (https://github.com/igniterealtime/Openfire/settings/secrets) called IGNITE_REALTIME_MAVEN_USERNAME and IGNITE_REALTIME_MAVEN_PASSWORD for someone who knows them.

I've added these secrets as organization-wide secrets (I assume we want to re-use them in plugin builds)

**Pull request merged**
