### PR TITLE
Fix implementation bug for XEP0049.

### PR DESCRIPTION
**Pull request by aztaru**
The comment in Line 105: "If the name and namespace of the element matches another" is correct, but the implementation is wrong, it checks "username and namespace" rather than "name and namespace".

### CODE REVIEW

**Comment by sco0ter** [comment]
This looks like everybody can now retrieve all the private data of all users, if they use the same name/namespace (usually if they use the same client). Certainly not what we want.
I think it should ask for "username", "name" and "namespace.

**Comment by aztaru** [comment]
You are right, The latest commit should meet the requirement.

**Comment by tevans** [comment]
Thanks for your contribution.

I believe you will also need to update the `get()` method to provide the additional parameter for the `LOAD_PRIVATE` sql statement.

**Comment by aztaru** [comment]
Done. :)

**Comment by tevans** [comment]
OK - looks good to me. :+1:

**Pull request merged**
