### PR TITLE
REST API update to 1.3.1

### PR DESCRIPTION
**Pull request by Redor**
Fixed: That created rooms were not propagated to other nodes OF-1535
Fixed: Missing documentation for "new" json mapping

### CODE REVIEW

**Comment by akrherz** [comment]
@Redor thanks, is there an actual code change here associated with OF-1535 ?

**Comment by Redor** [comment]
Good catch :) added it

**Comment by akrherz** [comment]
Just to verify that last commit is the change you wanted? Looks like a massive whitespace change

**Comment by Redor** [comment]
@akrherz yes it looks right. (Formatter kicked in and did a big whitespace change)

**Comment by lagix** [comment]
In Openfire 4.2.3 the REST API page shows blank

**Pull request merged**
