### PR TITLE
FIX: Monitoring plugin list request with max tag does not work correctly

### PR DESCRIPTION
**Pull request by ishmakov**
FIX: Monitoring plugin list request with max tag does not work correctly
https://community.igniterealtime.org/thread/56168

### CODE REVIEW

**Comment by ishmakov** [comment]
It's need to review by author or somebody, that it does not break other feature in Monitoring plugin.
At my first rewiew all are ok, but to be shure, better check it.

**Comment by leonroy** [comment]
I'll take a look.

**Comment by leonroy** [comment]
The SQL fu is strong with this one...that's one heckuva select and nice usage of GROUP BY. I don't think anyone's ever used GROUP BY in a single SELECT in the Openfire code base.

Going to fire up my test data and see if all the other monitoring queries still work ok fine,

thanks!

**Comment by leonroy** [comment]
Just looking at writing some integration tests to make verification of the monitoring plugin MUCH easier.

Do you know if there's a decent XMPP client which supports XEP-0136?

**Comment by ishmakov** [comment]
@leonroy Unfortunately I do not have a client, I write an extension gloox library.
But I spend testing via QIP client allows you to connect via the XMPP protocol and having a console, where you can send your XML request and read the response.

**Comment by dwd** [comment]
Sorry, this took me ages to get around to testing.

**Pull request merged**
