### PR TITLE
Jetty 12.0.14 ee8 upgrade

### PR DESCRIPTION
**Pull request by hqv126**

### CODE REVIEW

**Review by guusdk — CHANGES_REQUESTED** [review]
Hi @hqv126. Thanks for all the work that has gone into this!

The Jetty upgrade is a complex one. It will likely cause enough issues down the line (with regards to compatibility to plugins, etc) that it's important to carefully document what is being done, and why. In that light I'd like you to apply a number of changes:

1. The PR lifts Openfire Java dependency from 11 to 17, but didn't do that in all places where it's needed. Luckily, another PR (https://github.com/igniterealtime/Openfire/pull/2583) is already in the works for that. It might be best to revert the related changes in your PR, and rebase on the PR that's moving up the Java dependency instead.
2. I believe there might be unneeded changes in some of the commits. Please isolate those changes in separate PRs, and remove them from this PR. Having unneeded changes in the plugins makes it a lot more difficult to review the code (now, but also in the future, as we'll undoubtedly revisit our tracks at some point, to figure out what and why we did something).
3. Please refer to the ticket 'OF-2717' in the commit messages for this PR. This will allow for automation to kick in, so that we can easily trace the changes to and from the ticket in https://igniterealtime.atlassian.net/browse/OF-2717
4. As we've seen, this change breaks several plugins. Luckily, the breakage seems to be pretty similar across all plugins: you've identified a handful of errors. Please document the changes that are needed to fix those errors (preferably in a new HTML file under `/documentation/`). This will benefit both ourselves as third-party plugin developers.
5. I've noticed that your commit messages are a bit light on motivation. They describe _what_ is changed, but not _why_ that change was needed, or is beneficial. Including motivation is highly desirable for a complex change like this one, as it helps people to review this change. It will also help future maintenance of the code. If someone in the future is looking at this, they may want to know why something was done, to evaluate if their changes match with that.

**Comment by hqv126** [comment]
**Guss**: 2. I believe there might be unneeded changes in some of the commits. Please isolate those changes in separate PRs, and remove them from this PR. Having unneeded changes in the plugins makes it a lot more difficult to review the code (now, but also in the future, as we'll undoubtedly revisit our tracks at some point, to figure out what and why we did something).
**Huy**: Apart from the updates required to use Java 17—which will be addressed separately—the updates in this pull request resolve issues identified in this repository during the Jetty 12 and EE8 upgrade. Could you please point out the unnecessary changes so that I can address them?

**Guss**: 4. As we've seen, this change breaks several plugins. Luckily, the breakage seems to be pretty similar across all plugins: you've identified a handful of errors. Please document the changes that are needed to fix those errors (preferably in a new HTML file under /documentation/). This will benefit both ourselves as third-party plugin developers.
**Huy**: I’ve seen errors in the log for some plugins, which seem related to changes made in the PR. I don’t yet know the changes needed to fix these errors. I will:
1. List the plugin errors I have seen in a new HTML file under /documentation.
2. Raise a ticket to investigate and address these errors in more detail.

**Comment by guusdk** [comment]
> Apart from the updates required to use Java 17—which will be addressed separately—the updates in this pull request resolve issues identified in this repository during the Jetty 12 and EE8 upgrade. Could you please point out the unnecessary changes so that I can address them?

I recommend that you either [rebase ](https://docs.github.com/en/get-started/using-git/about-git-rebase) this PR on the new head of the `Main` branch, or create a new PR with only the required changes, whatever is easiest.

As for the unrelated changes: it's kind of hard to determine what changes are and are not strictly needed for the Jetty upgrade (that's why I also suggested to re-edit the commit messages), but I _think_ that at least the following changes should probably go in a distinct PR:
- Changes to the Plugin API usage (eg: `.getPluginByName("admin").orElseThrow()`)
- Updates to version numbers of Maven plugins
- Newly added Maven dependencies (xalan)

To be clear: if those changes are beneficial (but not really related to the Jetty upgrade), don't just delete them, but please create new PRs! 

> I’ve seen errors in the log for some plugins, which seem related to changes made in the PR. I don’t yet know the changes needed to fix these errors. I will:
>
> 1. List the plugin errors I have seen in a new HTML file under /documentation as part of this PR.

That sounds good! Please find out what changes are needed to fix the recurring errors for the plugins (as we'll need to fix those anyway, and that's quite a prerequisite for this change).

> 2. Raise a ticket to investigate and address these errors in more detail.

That would be super helpful. Please raise the tickets in the repositories for each of the plugins!

**Comment by hqv126** [comment]
Closing this pull request. Replaced by this PR: https://github.com/igniterealtime/Openfire/pull/2600/.

**Pull request closed without merging**
