### PR TITLE
Revert changes introduced via PR #300

### PR DESCRIPTION
**Pull request by tevans**
Restores earlier revision of the PluginClassLoader. 
Also, a minor fix to avoid using classes that are not part of the official JRE. This additional change was required to ensure a clean build.

### CODE REVIEW

**Comment by wmz7year** [comment]
I'm sorry for this.But my PluginClassloader idea is right? I'm testing all plugin and find issue.Then I'll create new pr.

**Comment by wmz7year** [comment]
I know the why some plugins not work. 
My PR put up isolation between plugins, including openfire.
When the plugin active use Openfire plugin resource,When you need to call Openfire not visible resulting in can not find, I will solve this problem in a new PR

**Comment by deleolajide** [comment]
This PR is responsible for multiple

java.lang.LinkageError: loader constraint violation: when resolving method "xxxxxxxxxxxx"

in the ofmeet plugin

**Comment by tevans** [comment]
Looks like I hosed this one up attempting to rebase. Will retry under separate cover.

**Pull request closed without merging**
