### PR TITLE
OF-1423 Honour configuration for message size

### PR DESCRIPTION
**Pull request by dwd**
Openfire already uses xmpp.parser.buffer.size as
the maximum stanza size in NIO client sessions.

This change ensures that this is also used when
configuring Websocket sessions.

### CODE REVIEW

**Comment by akrherz** [comment]
My only comment here is that `XMLLightweightParser.java` implements a property listener to change this "on the fly", it would be nice if this code did it as well, or is that possible?

**Comment by akrherz** [comment]
Oh, this is created for each new websocket connection?  If so, no worries then about a listener...

**Comment by dwd** [comment]
Oh, except I see a stupid typo.

**Comment by akrherz** [comment]
@dwd What typo are you referencing?

**Pull request merged**
