### PR TITLE
Plugin: userservice. Get REST responses in JSON too

### PR DESCRIPTION
**Pull request by alexproca**
Return responses from **userservice** REST plugin in json format too for easy consumption from javascript.
In order to get responses in JSON add header

**Accept: application/json**

### CODE REVIEW

**Comment by Redor** [comment]
Hi, thy for your contribution. Your PR looks good and I will merge it, but I would recommend you to take the REST API plugin, which contains all the userservice features. The only thing you need to change is the path of the URL (from userservice to restapi). The REST API plugin contains already the support of JSON (consuming and response). 

REST API documentation: https://www.igniterealtime.org/projects/openfire/plugins/restapi/readme.html

**Comment by alexproca** [comment]
Hello,

I know there is another api for all services but right now I need only acces to users. Maybe I’il look into REST API plugin to enable json too with another PR.

Best regards,
Alex Proca

**Comment by Redor** [comment]
REST API support already fully JSON.

**Comment by alexproca** [comment]
I did not look into it at all. Thanks for pointing that.

**Pull request merged**
