### PR TITLE
French translation full support

### PR DESCRIPTION
**Pull request by bernard-ng**
A part of the application is not fully translated into French, this pull request aims to finalize the French translation and correct potential translation errors

### CODE REVIEW

**Comment by gjaekel** [comment]
Dear Bernard,
welcome to the project and thank you for your contribution!
Guido

**Comment by gjaekel** [comment]
Dear Bernard,
If you have time an inclination, I would like to invite you to also have a look on the i18n file [src/i18n/pade_i18n.properties](https://github.com/igniterealtime/openfire-pade-plugin/blob/master/src/i18n/pade_i18n.properties) of the Pàdé plugin (https://github.com/igniterealtime/openfire-pade-plugin)
Thank you
Guido

**Comment by bernard-ng** [comment]
@gjaekel once I finish I will gladly do it

**Comment by gjaekel** [comment]
@bernard-ng Thank you in advance! We have to consult @deleolajide about, because it seems that I pointed out the wrong file.

**Comment by guusdk** [comment]
I'm excited to see this happen! @bernard-ng I understand that you are spending time on this whenever you have some time available, and that it will likely take some more time before it's finished. I have transformed this PR to one that is a 'draft'. Please mark it 'ready' when you're done! That will stop us from wondering if we can merge, or if we need to wait a bit for more translations to be added.

Also, I noticed that you appear to be translating the English texts that are already in the French i18n file. That's good, but you probably also need to add new lines to the French i18n files. I suspect that not everything that exists in the default file also exists in the French file.

**Comment by bernard-ng** [comment]
Thanks for the feedback @guusdk

**Comment by guusdk** [comment]
In each file, a translation key should exist only once. I do not know what happens if it occurs more than once.

**Comment by bernard-ng** [comment]
@guusdk I encounter an error on the http binding page

I checked out on the branch master with the latest changes online to make sure it wasn't me who introduced this error somehow, is there anything I can do to correct it? I don't see the possibility to create an issue on the project

<h2 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.el.ELException: Problems calling function [fn:escapeXml]</h2>

URI: | /http-bind.jsp
-- | --
500
javax.servlet.ServletException: javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.el.ELException: Problems calling function [fn:escapeXml]
org.jivesoftware.openfire.admin.http_002dbind_jsp
javax.servlet.ServletException: javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.el.ELException: Problems calling function [fn:escapeXml]
javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.el.ELException: Problems calling function [fn:escapeXml]
javax.el.ELException: Problems calling function [fn:escapeXml]
javax.el.PropertyNotFoundException: Property [CORSAllowOrigin] not found on type [org.jivesoftware.openfire.http.HttpBindManager]

<h3 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Caused by:</h3><pre style="color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">javax.servlet.ServletException: javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.el.ELException: Problems calling function [fn:escapeXml]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:162)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.el.ELException: Problems calling function [fn:escapeXml]
	at org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:905)
	at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:838)
	at org.jivesoftware.openfire.admin.http_002dbind_jsp._jspService(http_002dbind_jsp.java:354)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1459)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.jivesoftware.util.LocaleFilter.doFilter(LocaleFilter.java:73)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.jivesoftware.util.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:49)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.jivesoftware.admin.PluginFilter.doFilter(PluginFilter.java:174)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.jivesoftware.admin.AuthCheckFilter.doFilter(AuthCheckFilter.java:234)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	... 17 more
Caused by: javax.el.ELException: Problems calling function [fn:escapeXml]
	at org.apache.el.parser.AstFunction.getValue(AstFunction.java:194)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
	at org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(PageContextImpl.java:944)
	at org.jivesoftware.openfire.admin.http_002dbind_jsp$Helper.invoke4(http_002dbind_jsp.java:1812)
	at org.jivesoftware.openfire.admin.http_002dbind_jsp$Helper.invoke(http_002dbind_jsp.java:1892)
	at org.apache.jsp.tag.meta.admin.admin.contentBox_tagx.doTag(contentBox_tagx.java:118)
	at org.jivesoftware.openfire.admin.http_002dbind_jsp._jspx_meth_admin_005fcontentBox_005f3(http_002dbind_jsp.java:1305)
	at org.jivesoftware.openfire.admin.http_002dbind_jsp._jspService(http_002dbind_jsp.java:331)
	... 54 more
Caused by: javax.el.PropertyNotFoundException: Property [CORSAllowOrigin] not found on type [org.jivesoftware.openfire.http.HttpBindManager]
	at javax.el.BeanELResolver$BeanProperties.get(BeanELResolver.java:260)
	at javax.el.BeanELResolver$BeanProperties.access$300(BeanELResolver.java:212)
	at javax.el.BeanELResolver.property(BeanELResolver.java:333)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:92)
	at org.apache.jasper.el.JasperELResolver.getValue(JasperELResolver.java:113)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:169)
	at org.apache.el.parser.AstFunction.getValue(AstFunction.java:189)
	... 61 more</pre>

**Comment by guusdk** [comment]
Good catch. I also get that issue on that page, on the Master branch. That problem was introduced very recently (by me, sorry!).

I have fixed it in https://github.com/igniterealtime/Openfire/pull/2037. That fix has now been merged. When you rebase your changes to the current head of the Master branch, then you'll see that the problem is gone!

**Pull request closed without merging**
