### PR TITLE
OF-2905: Update Maven Wrapper to 3.3.2

### PR DESCRIPTION
**Pull request by guusdk**
These changes are the result of executing `./mvnw wrapper:wrapper`

### CODE REVIEW

**Comment by guusdk** [comment]
Weird that it removes the JAR file.

**Comment by Fishbowler** [comment]
> Weird that it removes the JAR file.

This is the `only-script` way, and is apparently the default now. https://maven.apache.org/wrapper/

**Comment by Fishbowler** [comment]
There's a second maven wrapper in build/ci/updater.
Ideally, I'd find a way to integrate this more neatly. In the meantime, I'm struggling to get `./mvnw wrapper:wrapper` to generate something similar to the root version, even down to the version of the wrapper in use :(

**Comment by guusdk** [comment]
Oh, that's a good find. I've got a slight preference for not changing the type of wrapper that we used, so I'll re-generate with

```
./mvnw wrapper:wrapper ./mvnw wrapper:wrapper -Dtype=bin
```

Within `build/ci/updater/` I'll try to do the same thing. It appears that we need an explicit environment variable for that plan to work. I've tried with the following from within that directory:

```
export OPENFIREVSN=5.0.0-SNAPSHOT && ./mvnw wrapper:wrapper -Dtype=bin
```

**Review by Fishbowler — APPROVED** [review]

**Comment by Fishbowler** [comment]
Approved but not merged, given all the activity currently happening in the project and its plugins.

Merge whenever you're ready for it, Guus.

**Pull request merged**
