### PR TITLE
Add Smack integration tests to Travis CI.

### PR DESCRIPTION
**Pull request by guusdk**
This commit adds steps to the Travis CI build script, that:
- start up Openfire after it finished building
- pulls in Smack
- executes the Smack integration tests

### CODE REVIEW

**Comment by akrherz** [comment]
consider adding an arbitrary `cat` of openfire's `all.log` ?

**Comment by GregDThomas** [comment]
And maybe even enable debug logging too.

**Comment by guusdk** [comment]
Not sure if I understand what you mean. For now, I'd be happy if this thing started to work in the first place...

**Comment by GregDThomas** [comment]
I think @akrkerz was suggestion that if the contents of logs/all.log were in the build log, it may help tracking down any problems. I was adding to that that enabling debug level logging may also prove beneficial.

**Comment by akrherz** [comment]
I think we need to close and reopen to get Travis back onboard

**Comment by akrherz** [comment]
sorry, gonna try close and open again now.

**Comment by akrherz** [comment]
#1293 is the path forward here.

**Pull request closed without merging**
