### PR TITLE
OF-2393: Update slf4j to 1.7.36

### PR DESCRIPTION
**Pull request by Neustradamus**
https://www.slf4j.org/news.html

### CODE REVIEW

**Comment by Fishbowler** [comment]
Something failed when you tried a higher version?

**Comment by guusdk** [comment]
@Neustradamus why update to slf4j 1.7.33 when version 1.7.36 currently is the latest release?

**Comment by Neustradamus** [comment]
1.7.36 fails, so we need to do 1.7.33, 1.7.34, 1.7.35 to see if the problem is here too.

**Comment by guusdk** [comment]
What do you mean with "1.7.36 fails"? When I update slf4j to version 1.7.36 on my local computer rebuild and start Openfire, I'm not immediately seeing any problem.

**Comment by Neustradamus** [comment]
The Openfire CI has failed when I have published for 1.7.36, have you looked why?

The log:
```
https://gist.github.com/Neustradamus/2bdba2c3974108d6e8f681379a62b181
```

**Comment by guusdk** [comment]
On first glance, I would say that this build failed because of a problem on the server that was doing the build:

```
Error:  error reading /home/runner/.m2/repository/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar; zip END header not found
```

That sounds as if a file is corrupt. My advise would be to clean caches, and try again.

**Comment by Neustradamus** [comment]
It is good, really strange the first Openfire CI test.

**Comment by guusdk** [comment]
Thank you!

**Pull request merged**
