### PR TITLE
OF-2030: FMUC persist config

### PR DESCRIPTION
**Pull request by guusdk**
This adds configuration persistency, by storing config to the database. As a result of adding this, some rework was needed. Basic testing seems to indicate that functionality has been preserved, but this could use further testing.

### CODE REVIEW

**Comment by guusdk** [comment]
While typing the comment for this PR, I realise that I've done some testing for FMUC functionality, but I didn't test if the configuration as filled out in the admin console was actually persisted (and usable after a restart). The docker-based setup that we're using to develop this gets cleaned up between restarts. I might need to acquire more docker foo...

**Comment by guusdk** [comment]
Hmm, one Smack integration test occasionally fails. I've not seen this failure before, and the test relates to MUC (which is what this PR relates to, too).

This is the failure as reported in the build leading up to this comment:
```
SEVERE: MultiUserChatIntegrationTest.mucDestroyTest (Normal) Failed
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.igniterealtime.smack.inttest.SmackIntegrationTestFramework.lambda$runTests$0(SmackIntegrationTestFramework.java:403)
	at org.igniterealtime.smack.inttest.SmackIntegrationTestFramework.runConcreteTest(SmackIntegrationTestFramework.java:478)
	at org.igniterealtime.smack.inttest.SmackIntegrationTestFramework.access$1600(SmackIntegrationTestFramework.java:77)
	at org.igniterealtime.smack.inttest.SmackIntegrationTestFramework$PreparedTest.run(SmackIntegrationTestFramework.java:680)
	at org.igniterealtime.smack.inttest.SmackIntegrationTestFramework.runTests(SmackIntegrationTestFramework.java:466)
	at org.igniterealtime.smack.inttest.SmackIntegrationTestFramework.run(SmackIntegrationTestFramework.java:228)
	at org.igniterealtime.smack.inttest.SmackIntegrationTestFramework.main(SmackIntegrationTestFramework.java:106)
Caused by: org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:35)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:162)
	at org.jivesoftware.smackx.muc.MultiUserChatIntegrationTest.mucDestroyTest(MultiUserChatIntegrationTest.java:148)
	... 11 more
```

**Comment by guusdk** [comment]
Curious. This seems to fail at line 148 of `MultiUserChatIntegrationTest.java` from Smack's 4.4.0-beta2 release, shown here:

https://github.com/igniterealtime/Smack/blob/6837c305e86593cf968dabf4fcfd45abb1ce05ec/smack-integration-test/src/main/java/org/jivesoftware/smackx/muc/MultiUserChatIntegrationTest.java#L126-L161

The test verifies a scenario where an occupant is leaving a room, but this failure seems to happen when the test fixture is being set up. More specifically, the test is being setup by having a user join a room (to later be removed from the room, which is the subject of the test). It is expected that at this time, the occupant count of the room is 1. This apparently is not the case.

**Comment by guusdk** [comment]
The same Smack integration test that is (occassionally) failing in this PR now causes an unrelated PR (https://github.com/igniterealtime/Openfire/pull/1725) to fail too. This makes it less likely that the cause is introduced by these PRs.

**Comment by guusdk** [comment]
I've conclusively found that the failing integration test `MultiUserChatIntegrationTest.mucDestroyTest` is due to a race condition in Smack. I've provided a fix for Smack in https://github.com/igniterealtime/Smack/pull/437

**Comment by guusdk** [comment]
I've disabled the offending test, and rebased this PR.

**Comment by Fishbowler** [comment]
Using https://github.com/surevine/openfire-docker-compose to set up 2 OF servers with a MUC on xmpp1 federated to a MUC on xmpp2.
After restarting all containers, federation continues as was
👍

**Comment by guusdk** [comment]
Thanks Dan!

**Pull request merged**
