### PR TITLE
MucRole code revised

### PR DESCRIPTION
**Pull request by yusufcakal**
Code Revised on Enum

### CODE REVIEW

**Comment by guusdk** [comment]
Hi! Thanks for your contribution! Why is this change desirable?

**Comment by yusufcakal** [comment]
Hi, It becomes a static code when the field number increases.
I chose such a way not to increase the number of switch cases at a later time.
The changes I have made are independent of the number of fields found in the enum and are more dynamic.

Thanks.

**Comment by guusdk** [comment]
Where you say "field number", you are referencing to the enum values, right?

Those are defined in a specification, and will never change.

Although I'm happy to improve code to resolve issues, I am reluctant to apply changes for the sake of change. I'd like to avoid over-optimization.

**Comment by yusufcakal** [comment]
Yes, I am at the threshold of enum values.
I see that I thought I could make more optimizations.
it does not matter
Have a good day.

**Pull request closed without merging**
