### PR TITLE
Remove unused webdav servlet

### PR DESCRIPTION
**Pull request by Fishbowler**
It was added for "future use" in 2007, and introduces some security warnings, which, whilst benign, are a good call to clean things up.

### CODE REVIEW

**Comment by Fishbowler** [comment]
This resolves 6 of the issues highlighted in the security dashboard by #1736

**Comment by akrherz** [comment]
You have any concerns with this @jadestorm ? :)

**Comment by jadestorm** [comment]
=)  I don't honestly even use Openfire anymore so... there's no real reason for me to have any concerns!  Glad to see Openfire is still trucking along though!

**Comment by guusdk** [comment]
> I don't honestly even use Openfire anymore 
😱

**Pull request merged**
