### PR TITLE
OF-2741: OSX Preferences Pane improvements

### PR DESCRIPTION
**Pull request by Fishbowler**
* Builds on modern Xcode
* Retires support for macOS 10.6-10.12, making 10.13 the latest supportable version (enforced by Xcode)

### CODE REVIEW

**Comment by Fishbowler** [comment]
Yes, it just needs finishing.

* remove the Jive logo 
* update the description of Openfire

**Comment by Fishbowler** [comment]
DMG:
image

Preferences Pane (Server):
image

Preferences Pane (About):
image

**Comment by Fishbowler** [comment]
I was hoping to fix the Preferences Panel not actually working to Start/Stop

I'm assuming it's some incremental OS changes that we haven't adapted for.

**Comment by bsherman** [comment]
I'm happy to give an approval, with the caveat, I don't currently have a mac for build or even to test with. :smiley:

**Review by bsherman — APPROVED** [review]
Looks good to me. But I was unable to build/test due to not having a capable system at this time.

**Comment by guusdk** [comment]
I'm perfectly happy to blame @bsherman lack of access to a capable system for any and all issues that pop up after merging this. :P

**Pull request merged**
