### PR TITLE
OF-953: Old JSP libraries should be upgraded.

### PR DESCRIPTION
**Pull request by guusdk**
By replacing Jetty 6.x era libraries with 9.x-based variants, JSP support
will be brought back up-to-date. Additionally, Openfire will no longer
have a mix of dependencies from various versions of Jetty. This commit
contains a number of changes that go hand-in-hand:
- Replaces JAR files
- Applies uniformity to the buildscript where JSPC is executed
- Replaces JSTL 1.0 taglibs with later versions
- Adds a simple logger to the build process (to stop it from complaining)

### CODE REVIEW

**Comment by tevans** [comment]
I noticed there were a handful of functional changes here and there in several of the plugins and the admin console. Hopefully we can enlist a few testing volunteers to give these components a shakedown after the merge.

Otherwise looks good. Thanks Guus!

**Comment by sco0ter** [comment]
I tried to build the old JSP pages with Maven and I got this error:

Failed to execute goal org.apache.sling:maven-jspc-plugin:2.0.8:jspc (compile-jsp) on project xmppserver: The absolute uri: http://java.sun.com/jstl/fmt_rt cannot be resolved in either web.xml or the jar files deployed with this application

I think the fixed taglibs should solve this issue. This PR is generally a good idea, although there are a lot of changes.

**Comment by akrherz** [comment]
@deleolajide Do you have a comment on this change? It touches Ofmeet.

**Comment by sco0ter** [comment]
Please note, that I rebased this branch on master, resolved the conflicts and pushed it the branch `guusdk-OF-953`.

**Comment by deleolajide** [comment]
@akrherz , thanks for the heads up. +1 for the change and I will have to resolve any issues that crop up.

**Comment by akrherz** [comment]
committed to master, thanks to @sco0ter rebase

**Pull request closed without merging**
