### PR TITLE
OF-1428: Delete the long-deprecated Coherence based clustering plugin

### PR DESCRIPTION
**Pull request by GregDThomas**
The Coherence based clustering plugin was deprecated in May 2013, and was stated as being compatible with Openfire 3.8.x only.

Furthermore, OF-173 might require changes to the Cache interface, and it seems superfluous to have to make those changes to the Coherence plugin too.

### CODE REVIEW

**Comment by dwd** [comment]
Totally in favour of this.

**Comment by guusdk** [comment]
Ah, yes, I'd not be sorry to see this one go. Just to cover our bases, let's get some feedback from others. @akrherz, @speedy01, @tevans @wrooot - thoughts?

**Comment by speedy01** [comment]
I'm good with it.

**Comment by tevans** [comment]
+1 - no tears will be shed  :)

On Nov 14, 2017, at 3:36 AM, Guus der Kinderen <notifications@github.com<mailto:notifications@github.com>> wrote:


Ah, yes, I'd not be sorry to see this one go. Just to cover our bases, let's get some feedback from others. @akrherz<https://github.com/akrherz>, @speedy01<https://github.com/speedy01>, @tevans<https://github.com/tevans> @wrooot<https://github.com/wrooot> - thoughts?

**Comment by wrooot** [comment]
Wait! I want it back!
Joking ;)

**Pull request merged**
