### PR TITLE
OF-1120 Change default behavior of Email on Away plugin

### PR DESCRIPTION
**Pull request by wrooot**

### CODE REVIEW

**Comment by wrooot** [comment]
Anyone? This is a very simple fix. Essentially fixing my previous PR :)

**Comment by wrooot** [comment]
I have synced my fork with the master and it had added another commit to this PR after i have pushed changes back to fork after merging with upstream. Not sure if this is bad or not, but honestly, such a simple PR hanging for 2 weeks? It can be squashed while doing merge.

**Comment by akrherz** [comment]
cherry picked as https://github.com/igniterealtime/Openfire/commit/279a998fd8727c49eecb8037d590de4ae672d8cc

I am unsure what happened with your second commit of changes

**Comment by wrooot** [comment]
Thanks. Well, will have to clone new fork then.

**Pull request closed without merging**
