### PR TITLE
ci: ensure aioxmpp test failure fails

### PR DESCRIPTION
**Pull request by akrherz**

### CODE REVIEW

**Comment by guusdk** [comment]
What confuses me: how can this be needed, if we also have seen build failures when aioxmpp tests failed?

**Comment by Fishbowler** [comment]
And yet https://github.com/igniterealtime/Openfire/actions/runs/9762610073/job/26948168922?pr=2482 is clearly both a failure and a green tick :thinking:

**Comment by guusdk** [comment]
Regardless, I'm happy to include this, as it will make things better (c)(r) ... but I don't understand it.

**Comment by akrherz** [comment]
This commit is included with #2482 for the `4.8` branch

**Pull request merged**
