### PR TITLE
add possibility to store complete stanza in archive

### PR DESCRIPTION
**Pull request by Hammington**
in the settings there is now a switch allowing to add complete stanza to
the archive for muc conversations

### CODE REVIEW

**Comment by akrherz** [comment]
@Hammington Does this addres https://issues.igniterealtime.org/browse/OF-817 ?

**Comment by Hammington** [comment]
@akrherz I think this is not the same as this issue refers to the internal muc-serrvice history and my change adresses the mam-service implementation included in the monitoring plugin.

**Comment by Hammington** [comment]
@guusdk the stanza is stored in the table OFMESSAGEARCHIVE and can be retrieved through mam-queries, the code for storing the stanza was already available but the stanza was always set to empty string.

**Comment by akrherz** [comment]
cherry-picked patch onto master

**Pull request merged**
