### PR TITLE
Fixed group population for colliding full names.

### PR DESCRIPTION
**Pull request by anuko**
When LDAP search returns a multiple result set for a user CN,
we now iterate through the entire set to find a matching user DN.

### CODE REVIEW

**Comment by guusdk** [comment]
I don't see how this PR breaks the unit test (as Travis reported).

Otherwise, +1. 

@speedy01 care to review?

**Comment by guusdk** [comment]
Re-fired Travis, now all green.

**Comment by sco0ter** [comment]
+1

**Comment by tevans** [comment]
+1

**Comment by wrooot** [comment]
Filed as https://igniterealtime.org/issues/browse/OF-1041

**Comment by guusdk** [comment]
Hmm. In hindsight: would a better solution to the problem that this PR tries to solve be: make sure that the ```manager.getUsernameField()``` method returns a value that uniquely identifies a user? The value for that method is configurable through the ```ldap.usernameField``` property. Would the PR be unneeded if @anuko had set ```ldap.usernameField``` to "distinguishedName" for their setup?

**Comment by guusdk** [comment]
I've created a PR to revert the change here: https://github.com/igniterealtime/Openfire/pull/509

**Comment by guusdk** [comment]
Reading up on the subject a bit more, I don't believe that my suggested workaround would work. Nonetheless, what's in place now is not portable to other LDAP providers than Active Directory, and should be reverted.

**Pull request merged**
