### PR TITLE
New plugin ipfs

### PR DESCRIPTION
**Pull request by deleolajide**
This plugin turns openfire into a node/peer on the IPFS network
It will allow a federation of openfire servers to share assets and resources
Plugins can access the ipfs instance/node via the ipfs-java client library.

### CODE REVIEW

**Comment by dwd** [comment]
I'm really not convinced this ought to be in the main Openfire repository. Entirely happy, of course, for it to be elsewhere and available via the website etc.

**Comment by deleolajide** [comment]
> I'm really not convinced this ought to be in the main Openfire repository. Entirely happy, of course, for it to be elsewhere and available via the website etc.

That exactly what you said last time I submitted a plugin to the internal plugins folder in openfire.

I think very carefully before I decide where my plugins go. Sometimes it is my personal repo, sometimes it is standalone repo on ignite and sometimes it is the plugins folder of openfire repo. This one belongs with openfire. I suspect that the ipfs binaries could be causing concern, but there are other plugins with embedded binaries.

What exactly are the guidelines for internal vs external openfire plugins? XEPs only?

The problem with external plugins that are tightly coupled with Openfire is that they break when architectural changes are made to Openfire. You have to deal with a fair bit of changes at once with no context unlike an internal plugin that triggers a build failure and immediate action with context.

**Comment by akrherz** [comment]
@deleolajide I think what we are striving for here is to generally remove plugins from the Openfire github source tree and start placing these plugins within their own dedicated igniterealtime organization repositories.  The recent migration to maven certainly makes this much easier and the recent [example plugin](https://github.com/igniterealtime/openfire-exampleplugin) I think is the goal in mind here.

CI and our bamboo can handle the auto-build failure stuff.

**Comment by deleolajide** [comment]
>The recent migration to maven certainly makes this much easier and the recent example plugin I think is the goal in mind here.

I appreciate that and that is why the [solo plugin](https://github.com/igniterealtime/Solo) has its own repo. However, I have seen other plugins land in Openfire as internal plugins since Openfire Meetings was pushed out for this same reason. If I did not know any better, I might think it was personal.

>CI and our bamboo can handle the auto-build failure stuff.

One of the privileges of being an internal plugin is that when Openfire changes and breaks your plugin, you get to know immediately via auto-build. You get the context of the change and can apply a fix asap with no fuss.

When you are a second class external plugin, the exercise of applying several changes to your plugin to keep it in sync with Openfire months after is just **painful** especially when it becomes an **unplanned** exercise with a **live** customer.

This plugin will be tightly coupled to Openfire APIs. I could do with some help here

**Comment by akrherz** [comment]
@deleolajide 
> If I did not know any better, I might think it was personal.

Drop the drama.  You know as well as anybody that we are desperately short on developers.

**Comment by deleolajide** [comment]
>Drop the drama. You know as well as anybody that we are desperately short on developers.

Agreed. Repeated rejection and painful experiences does make one become emotive and induce drama. In any case, I am sorry.

**Comment by guusdk** [comment]
@deleolajide, for what it's worth: I'd prefer at least some of your plugins to be in a dedicated repository, rather than be part of the Openfire source code, for one of these reasons:

- the functionality added by the plugin is very feature-rich, to an extend that it's hardly a plugin anymore, but almost a stand-alone application.
- Some plugins appeal most to very specific groups of users but not offer a 'simple addition' to the Openfire-server features (like, say, a plugin that resizes an avatar).
- Some of the plugins are really big (in byte size), making their inclusion in the (already very big) Openfire source undesirable.

Most of the plugins that you produce tend to tick at least one of these boxes, but often a combination. That is perhaps why you observe that many of 'your' plugins get treated somewhat differently to other, mostly much smaller (in many senses of the word) plugins. Let me guarantee you though that there's not any _personal_ motive at play (if anything, I value our interaction, even if I've been not as much on top of things in the last few weeks).

**Comment by deleolajide** [comment]
>Let me guarantee you though that there's not any personal motive at play (if anything, I value our interaction, even if I've been not as much on top of things in the last few weeks).

Thank you for the kind words.

I agree that this ipfs plugin does tick box 3 and I am willing to mavenise the ipfs binaries to reduce the size. Apart from that, creating a swarm of federated openfire servers in a trust-less decentralised network is a very useful addition to Openfire's features and won't work if the ipfs plugin is considered an application and not a optional server feature. It needs to get as close as possible to the httpfileupload plugin and openfire server APIs that it will depend on.

I already have application plugins like Solo (that already lives in dedicated repository) queuing up to use its features.

**Comment by deleolajide** [comment]
Moving this plugin to a stand-alone repository on ignite realtime

**Comment by akrherz** [comment]
Great, if you got a plugin jar file to distribute, please let me know where it is and I'll add to the website!

**Comment by deleolajide** [comment]
https://github.com/igniterealtime/IPFS/releases

thank you

**Comment by akrherz** [comment]
Eh, I tried and it ended up crashing our JSP page, will investigate more later
```
org.apache.jasper.JasperException: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:565)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:481)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
Root Cause

java.lang.IllegalArgumentException: Comparison method violates its general contract!
	java.util.TimSort.mergeHi(TimSort.java:899)
	java.util.TimSort.mergeAt(TimSort.java:516)
	java.util.TimSort.mergeForceCollapse(TimSort.java:457)
	java.util.TimSort.sort(TimSort.java:254)
	java.util.Arrays.sort(Arrays.java:1438)
	org.apache.jsp.projects.openfire.plugins_jsp._jspService(plugins_jsp.java:317)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
```

**Comment by deleolajide** [comment]
The actual link is https://github.com/igniterealtime/IPFS/releases/download/v0.0.1/ipfs.jar

**Comment by akrherz** [comment]
I spent a while attempting to resolve this and can't.  the common suggestion is to set a JVM property `java.util.Arrays.useLegacyMergeSort` to workaround this, but alas, that feels odd to me.  Even worse, I can't reproduce this on my development laptop and the jar file is used just fine by the website.  sigh

**Comment by akrherz** [comment]
I implemented the `java.util.Arrays.useLegacyMergeSort` workaround for ignite's tomcat and the plugin is now available for download from there.

**Pull request closed without merging**
