### PR TITLE
OF-1408 Show the cache expiry time on the caches page

### PR DESCRIPTION
**Pull request by GregDThomas**
This PR simply displays the cache expiry time (in milliseconds, if any) on the Cache Summary page.

image

### CODE REVIEW

**Comment by GregDThomas** [comment]
A couple of things 
a) joda-time has a nice PeriodFormat class which will prettily format a duration (e.g.  21600000 -> "6 hours", but it seems overkill to add yet another dependency just for this one page.
b) I've added an english entry to all the i18n files for the new column header - I'm not sure if that's strictly necessary - does it default to english if a country specific version is not present?

**Comment by akrherz** [comment]
@GregDThomas Thanks, please consider opening Jira issues ahead of the PR so that your code change can be associated with an issue.  Currently, the issue workflow is how we generate the changelog :/

**Comment by GregDThomas** [comment]
Thanks - I hadn't realised I had JIRA creation rights. Now i do - raised at https://issues.igniterealtime.org/browse/OF-1408

**Comment by yuan24zz** [comment]
How to store online chat records into  table ofoffline column “stanza” like offline chat

**Comment by guusdk** [comment]
@yuan24zz Please do not comment on PRs with unrelated questions. Please ask your questions in https://discourse.igniterealtime.org/

**Comment by guusdk** [comment]
This is a nice addition. I agree that adding a new library is overkill, but we might have something for this. Is something like this re-usable? https://github.com/igniterealtime/Openfire/blob/master/src/web/index.jsp#L211

**Comment by GregDThomas** [comment]
`StringUtils.getElapsedTime(long)` is certainly a good starting point; I think I might need to create a new version, say `StringUtils.getFullElapsedTime(long)` , to make it more useful in this case as "Less than 1 minute" is perhaps less than ideal.

**Comment by guusdk** [comment]
Whatever suits you - I'd not invest to much time though :)

**Comment by GregDThomas** [comment]
Here you go - a definite improvement, IMHO.

image

**Pull request merged**
