### PR TITLE
OF-1929: Make LDAPS the default protocol

### PR DESCRIPTION
**Pull request by GregDThomas**
In addition to that;
a) Tidied up Boolean settings in LDAPManager which has been bugging me for ages (!), and
b) Brought the LDAP encryption settings out of "Advanced" and highlight when using plain text

image

image

### CODE REVIEW

**Comment by guusdk** [comment]
Awesome!

Is this a good place to also address the issue that you reported earlier, here https://github.com/igniterealtime/Openfire/pull/1518#discussion_r347406092 ?

**Comment by GregDThomas** [comment]
> 
> 
> Awesome!
> 
> Is this a good place to also address the issue that you reported earlier, here [#1518 (comment)](https://github.com/igniterealtime/Openfire/pull/1518#discussion_r347406092) ?

Done - though this did turn up a bug where some properties only ever took the default values (!) - now fixed.

**Comment by GregDThomas** [comment]
I should add that I've only tested this with LDAPS - as that's all the only LDAP server I have ready access to supports.

**Comment by guusdk** [comment]
Woooow - lots of options were never used! Good find!

**Pull request merged**
