### PR TITLE
OF-122: MUC subject change policy

### PR DESCRIPTION
**Pull request by tevans**
Default to lenient policy, allowing override to strict (conforming)
policy. Tested using Pidgin, Psi, and Exodus. Refer to details in
OF-122.

### CODE REVIEW

**Comment by sco0ter** [comment]
To be honest, I don't like to violate the spec and let buggy clients think they are doing it right. This surely won't encourage them to fix their bugs.

I think XEP-0045 is clear enough on the subject change, not vague.

At least make the spec-conform behavior the default one.

**Comment by tevans** [comment]
Agree in principle ... however in this case enforcing the strict behavior (in the server) effectively allows non-conforming clients to change the room subject without permission. This is because groupchat messages having both a subject and a body are (incorrectly) treated as subject change requests by these clients.

I think the proposed implementation is correct given the problems with the specification.

**Comment by sco0ter** [comment]
But this is still a client issue. Why should we care about some non-conforming clients displaying a subject change, which isn't a real subject change as per the spec.
It sounds as if these clients treat "subject + body" in messages as subject change, but I fail to see, why this Openfire's concern.

**Comment by tevans** [comment]
OK - I actually have made the same assertions in the comments of OF-922. I will adjust this patch to conform to the spec by default, allowing strict=false via a configuration override.

**Comment by dwd** [comment]
+1

**Pull request merged**
