### PR TITLE
OF-1660: Generate javadoc artifacts as part of the verify phase

### PR DESCRIPTION
**Pull request by GregDThomas**
`mvn verify` will now generate javadoc and sources jar files too.

`mvn package` does not - as the generation can be slow which is a PITA during the dev/test cycle.

### CODE REVIEW

**Comment by GregDThomas** [comment]
Note; still requires the artifact to be moved to the right place.

**Comment by guusdk** [comment]
I'm not a big fan to attaching this to a Maven phase where this action is unexpected. Can't we instead use either a profile, or an explicit additional argument in the maven command?

**Comment by GregDThomas** [comment]
I hear what you're saying; the default phase for packaging javadoc/source files is, well, "package" - I pushed it back to verify to cut down the dev/test cycle time. 

Does the CI build things with a specific profile? Could it do so?

**Comment by guusdk** [comment]
Thank you! Moving the artifact to the right place will first require us to move it into the Maven repository. If you have time left, maybe look at [line 17](https://github.com/igniterealtime/Openfire/blob/b6c34a27bd006ac3e8a31061e316e5cabc92ad43/.travis.yml#L17)?

**Comment by GregDThomas** [comment]
Well, I changed that line too, I think it's right, but may need to be merged before anything happens?

**Comment by guusdk** [comment]
It's probably a good thing that Travis does not deploy anything to our Maven repo based on an unmerged PR. :)

**Pull request merged**
