### PR TITLE
Added jar dependency to callbackOnOffline plugin

### PR DESCRIPTION
**Pull request by k-misztal**
I added `jersey-media-json-jackson-2.26.jar` dependency for callbackOnOffline plugin. Issue was mentioned here #981 .

### CODE REVIEW

**Comment by hkauroberoi** [comment]
Hi,
I had to rebuild the plugin with few extra lines of code as in the logs it showed that my URL is being hit while actually it never did. Can you please check !!

**Comment by forEst0620** [comment]
Hi.
Unfortunately, callbackonoffline plugin never works to me.
Please send me the callbackonoffline jar file that works fine on your xmpp server.
Additionally, please let me know your jre and openfire version.

**Comment by forEst0620** [comment]
Hi hkauroberoi
Could you tell me about your openfire version and jre version?
My openfire version is 4.1.4 and jre version is 1.8.
Is it too old?

**Comment by hkauroberoi** [comment]
Sure... will do in a moment !!

**Comment by hkauroberoi** [comment]
Hi,

Attached is the jar file. Please make sure that you add your url to
plugin.callback_on_offline.url  property in the server properties. In case
you need to know how my api works, lemme know !!

Rename the file to .rar, extract it and the password is stopnsolve.

Lemme know if thrs any issue..

Thanks - Kapil Oberoi

**Comment by forEst0620** [comment]
Hi hkauroberoi.
Where can i find the attached jar file?
Could you send me the jar file please?

**Comment by hkauroberoi** [comment]
https://drive.google.com/file/d/1f6qF0X9NWxizshE6LDuPUzzPLobZ7pBU/view?usp=drivesdk

On 2 Mar 2018 6:19 am, "forEst0620" <notifications@github.com> wrote:

Hi hkauroberoi.
Where can i find the attached jar file?
Could you send me the jar file please?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/igniterealtime/Openfire/pull/1030#issuecomment-369782692>,
or mute the thread

**Comment by forEst0620** [comment]
Hi hkauroberoi
Thanks a lot.
Have a great weekend!!!

**Comment by hchouhan02** [comment]
Hi, 
I tried with the latest plugin available on OpenFire but getting an error while calling callback URL via POST method. It will be helpful if you can provide jar file link again. 
Thanks.

**Pull request closed without merging**
