### PR TITLE
Revert "OF-1542: Apply filtering to the user summary page"

### PR DESCRIPTION
**Pull request by guusdk**
This reverts (most of) commit e1ee7a3c75b8110f921ae23b038d32cdd086d757.

The changes in the original commit caused all users to be obtained from
the user provider when looking at the user-summary page. For instances
with many users, this requires to much resources and takes to long to
complete.

### CODE REVIEW

**Comment by guusdk** [comment]
@GregDThomas do you see another solution to this? I'd love to retain the functionality, if possible.

If all else fails, maybe have some kind of hard-coded limit under which the filtering is applied, but above which it is not?

**Comment by guusdk** [comment]
CPU's on Ignite are still burning, even with this revert. Something else must be up.

**Comment by GregDThomas** [comment]
(I see the Group Chat is not responding; I wonder if it's the LDAP server itself which is causing the problem, and needs a swift kicking?)

**Comment by akrherz** [comment]
@GregDThomas LDAP shouldn't be at play for ignite.  I see that groupchat is hanging on the second bosh request.  Erm

**Comment by akrherz** [comment]
@GregDThomas the cpu spinning starts with the first BOSH connection

**Pull request merged**
