### PR TITLE
OF-997 Deny framing to avoid clickjacking

### PR DESCRIPTION
**Pull request by dwd**

### CODE REVIEW

**Comment by guusdk** [comment]
Perhaps SAMEORIGIN instead of DENY is more suitable here? I bet that there are instances out there that are embedded in some kind of larger management console.

**Comment by dwd** [comment]
Perhaps it's most sensible to make it an option.

**Comment by deleolajide** [comment]
YES, there are few instances that we have of Openfire embedded in a customer portal. Please put this behaviour behind JiveGlobal property for backward compatibility.

**Comment by dwd** [comment]
That better?

**Comment by guusdk** [comment]
works for me. +1

**Comment by deleolajide** [comment]
+1 Excellent. many thanks :-)

**Pull request merged**
