### PR TITLE
Presence probe for local user is not allowed when probee not subscribed

### PR DESCRIPTION
**Pull request by Sentient07**

### CODE REVIEW

**Comment by Flowdalic** [comment]
Thanks for your contribution. Unfortunately it's hard to spot the actual changes in your commit since it contains a lot of whitespace non-semantic changes. Ideally your commit should only contain semantic changes.

**Comment by Sentient07** [comment]
hi, @Flowdalic sorry about that. I've now changed the commit to contain only semantic changes.

**Comment by dwd** [comment]
Can you squash (and rebase) these changes into a single commit, and update the PR? The following should do it:

git remote add upstream git@github.com:igniterealtime/Openfire.git
git fetch upstream
git rebase upstream/master
git rebase -i upstream/master  # Change second patch's command to 'f'
git push origin +PresencePatch

Otherwise it looks great.

**Comment by dwd** [comment]
Rebased; merged.

**Pull request closed without merging**
