### PR TITLE
OF-1347: Improve Admin Console Group Edit page

### PR DESCRIPTION
**Pull request by guusdk**
This commit adds some UX improvements to the 'edit group' page on the admin console.

### CODE REVIEW

**Comment by akrherz** [comment]
Thanks @guusdk !  I pulled this in, built it successfully and played with the interface

 - The concept of Group admins remains, is this even used anywhere?
 - I like the disabled UI for shared group

I tried various things and didn't find any bugs.

**Comment by guusdk** [comment]
Thanks for checking! I honestly don't know if the purpose of admins serves any purpose. I assumed so, and retained the functionality (there's quite a bit of code involved, actually). If they indeed serve no purpose, we might want to remove them - but lets do that in a dedicated issue/PR.

**Comment by deleolajide** [comment]
Please don't pull out the group admins feature. We use it in telecoms. Groups are used for user roles and entitlement provisioning. Very effective  when Openfire is connected to Active Directory.

**Comment by guusdk** [comment]
Good to see someone is using it after all. :) The current code in Openfire does not make use of this feature at all, I think. Is there any generic bit from your application that you can/want to push upstream, @deleolajide ?

**Comment by deleolajide** [comment]
We are not doing anything generic that can be pushed upstream, we just get the group admin users of a group like this

````
			JSONArray adminsJSON = new JSONArray();
			int i = 0;

			for (JID memberJID : group.getAdmins())
			{
				JSONObject adminJSON = new JSONObject();
				adminJSON.put("jid", memberJID.toString());
				adminJSON.put("name", memberJID.getNode());
				adminsJSON.put(i++, adminJSON);
			}
			groupJSON.put("admins", adminsJSON);
````

**Pull request merged**
