### PR TITLE
OF-988: Don't queue packets twice.

### PR DESCRIPTION
**Pull request by guusdk**

### CODE REVIEW

**Comment by dwd** [comment]
No idea how this could possibly fail. Looks good to me.

**Comment by guusdk** [comment]
Yeah, I can't figure that out either. The test runs fine locally. Maybe a fluke?

**Comment by akrherz** [comment]
I asked travis to attempt to rebuild and it failed again in the same matter, strange.

**Comment by guusdk** [comment]
Ther's no need for this any longer, as the code that is fixed by this PR was reverted by https://github.com/igniterealtime/Openfire/pull/423

**Pull request closed without merging**
