### PR TITLE
OF-881: NIOConnection Thread Deadlock when two clients in each others ro...

### PR DESCRIPTION
**Pull request by aultuser**
...ster simultaneously disconnect

### CODE REVIEW

**Comment by akrherz** [comment]
@aultuser  awesome job to get signed up for github and submit an immediate PR :)  One item of note, it is best to submit PRs from branches and not your master.  When you submit a PR from your master, it will cause some troubles as upstream master move along without first taking this PR.

**Comment by aultuser** [comment]
@akrherz Thanks for the information.  Would you like this PR closed, and a new PR opened from a branch?

**Comment by akrherz** [comment]
@aultuser I don't think that is necessary, but perhaps others have a more educated opinion.  Hopefully one of the devs can evaluate this one line patch quickly.

**Comment by dwd** [comment]
This looks great. The master branch thing for pull requests really only affects you, not us, so I'll just merge this in a few minutes.

**Pull request merged**
