### PR TITLE
OF-2192 - Admin: Add version info to Session Summary

### PR DESCRIPTION
**Pull request by Fishbowler**
Fixes https://igniterealtime.atlassian.net/browse/OF-2192

Incorporates community feedback: https://discourse.igniterealtime.org/t/client-sessions-column-chooser/89434

### CODE REVIEW

**Comment by Fishbowler** [comment]
Hmmm. Not quite ready yet. Gotta get the JSP to work on all versions of Java...

**Comment by gjaekel** [comment]
At the first look, I also don't see the syntactical difference between L41 and L44 ...
```
 41:         <%= StringUtils.escapeHTMLTags(sess.getAddress().getResource()) %>
42:     </td>
43:     <td width="15%" nowrap>
44:         <%= ((sess.getSoftwareVersion() !== null && sess.getSoftwareVersion().get("version") !== null ) ? StringUtils.escapeHTMLTags(sess.getSoftwareVersion().get("version")) : "" ) %>
45:     </td>
```

**Comment by Fishbowler** [comment]
Suspect it's how null checking works in JSP that I've not got a grip of. I picked this one up entirely because this is a weak area of mine. I'll figure it out today though. It's all on StackOverflow, right? :)

**Comment by gjaekel** [comment]
> It's all on StackOverflow, right? :)

There's to much on StackOverflow!

**Comment by Fishbowler** [comment]
Fixed.

**Review by akrherz — APPROVED** [review]

**Pull request merged**
