### PR TITLE
OF-1041: Revert "Fixed group population for colliding full names."

### PR DESCRIPTION
**Pull request by guusdk**
This reverts commit fb9c6a39a37461b94d9eecec559eac8b4e88d458.

### CODE REVIEW

**Comment by guusdk** [comment]
This undoes https://github.com/igniterealtime/Openfire/pull/474

**Comment by tevans** [comment]
+1

**Comment by guusdk** [comment]
A alternative is provided in #511

**Comment by guusdk** [comment]
Closing. Merging #511 instead.

**Pull request closed without merging**
