### PR TITLE
PubSubPersistenceManager - Incorrect syntax near the keyword 'LEFT'

### PR DESCRIPTION
**Pull request by promiselaoliu**
Fix the SQL syntax error for sqlserver and oracle.

### CODE REVIEW

**Comment by GregDThomas** [comment]
Hi; thanks for the contribution; this looks, to me, good to merge - can you confirm you've no more changes? 

(ref: https://issues.igniterealtime.org/browse/OF-1657)

**Comment by promiselaoliu** [comment]
Yes, currently there's no more changes from me.
Thank you Greg.

**Comment by promiselaoliu** [comment]
Note that my solution has only covered sqlserver and oracle, because DB2 is not supported in our product.

**Comment by GregDThomas** [comment]
Thanks again!

**Pull request merged**
