### PR TITLE
OF-1770 Include nickname in MUCEventListener.occupantLeft

### PR DESCRIPTION
**Pull request by danielhams**
This one breaks API contracts unfortunately. As far as I can tell the OF "MonitoringPlugin" at least has impact from this change (GroupConversationInterceptor).

Background: We have a chunk of functionality we hang off join and leave events to MUC rooms. Having the nickname lets us skip some of the DB queries or "remembering" we otherwise would need to do in building our audit events.

### CODE REVIEW

**Comment by danielhams** [comment]
Aha! great, someone has skills in the "keeping an API compatible" department :-)

I'll take a look.

**Comment by GregDThomas** [comment]
PS. 
> someone has skills in the "keeping an API compatible" department

That includes you, now :)

**Comment by akrherz** [comment]
Sorry @danielhams , could you look into rebasing this?  If you are busy, I can give it a swing.

**Comment by danielhams** [comment]
@GregDThomas @akrherz 

Thank you gents!

**Pull request merged**
