### PR TITLE
Added User Status Plugin

### PR DESCRIPTION
**Pull request by annovanvliet**
Plugin from Stefan Reuter to keep a history of the user status in the
database.

### CODE REVIEW

**Comment by akrherz** [comment]
Thank you very much for doing this, let us see if @srt is good with this...

**Comment by dwd** [comment]
This looks fine, although:
* Are the Javadoc corrections in the User Import/Export plugin code intentional?
* Do we know the original license? It seems unclear if the original code were licensed under Apache 2 or compatible?

**Comment by annovanvliet** [comment]
the ImportExportPlugin JavaDoc change was intentional, but is a little misplaced. My bad habit of fixing IDE complaints on the fly. I worked in the past on this code and fixed now the javadoc.

**Comment by annovanvliet** [comment]
About the license: The original code did not contain any license declaration, only a copyright statement in the readme and changelog. Something should probably be added to the sources.

**Comment by akrherz** [comment]
I've directly emailed @srt now about this.  [This forum post](https://discourse.igniterealtime.org/t/user-status-plugin/77533) regarding the plugin mentions a GPL license.

**Comment by srt** [comment]
I am fine with the plugin being merged upstream. Regarding the license I am open for whatever fits the eco system best.

**Comment by akrherz** [comment]
I needed to update the plugin versioning as we still support ant builds :/

**Pull request merged**
