### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Fishbowler**
Fixes a bunch of CVEs.
Doesn't touch Mina.
Suppresses one false positive from JDOM2, which is included by Rome for RSS, but isn't used in a way that could expose the problem.

### CODE REVIEW

**Comment by Fishbowler** [comment]
There's one more to resolve that I'll save for later - Jetty should go to 9.4.44 rather than 9.4.43, but the jasper JSP compiler won't compile our pages there :thinking:

**Comment by guusdk** [comment]
Note that I'm trying to take out Ant completely in https://github.com/igniterealtime/Openfire/pull/1912/

**Comment by Fishbowler** [comment]
We'll merge #1912 first, then deal with the rebase :+1:

**Comment by Fishbowler** [comment]
^ Done this, awaiting CI

**Pull request merged**
