### PR TITLE
OF-1797 Accelerate loading MUC rooms

### PR DESCRIPTION
**Pull request by abe-ta**
Hi, I tested Openfire 4.2.3 with 200,000 MUC rooms. And I found out loading MUC rooms can be very slow in proportion to the number of rooms. In my case, it needed over 1 hour to start Openfire.
I identified the cause in MUCPersistenceManager. (This problem still exists in Openfire 4.3 or later)
- After fetching MUC rooms from `ofmucroom` table, each `LocalMUCRoom` loads its default properties from `ofmucserviceprop` table with MUCPersistenceManager. This process calls `SELECT` SQL about 200,000 * 12 times (the 12 is the number of LocalMUCRoom.xxx fields). In the end, the more MUC rooms the more time needed.

I tweaked MUCPersistenceManager.getProperty just a little bit. By this fix, Openfire startup time become about 90 seconds in 200,000 MUC room.

Please review.

### CODE REVIEW

**Comment by akrherz** [comment]
Thanks, this seems good to me, but will let others weigh in.

**Comment by guusdk** [comment]
Thank you for your suggestion. That, indeed, would dramatically improve things in large instances.

Can we further improve your change by applying thread safety, by replacing the entire method content with this?

```java
        final MUCServiceProperties props = propertyMaps.computeIfAbsent( subdomain, MUCServiceProperties::new );
        return props.get(name);
```

**Comment by guusdk** [comment]
Upon closer inspection, I've found various other places in the same class that would benefit from your change. Would you mind applying it to all applicable places? I'd advice you to look at all invocations of the constructor of `MUCServiceProperties`

**Comment by abe-ta** [comment]
Thanks for your great proposal! I fixed, and there was no problem launching Openfire and loading each settings.

**Comment by guusdk** [comment]
Excellent! Did you verify that you still have the performance benefits from your original code?

**Comment by abe-ta** [comment]
Openfire startup time remained 90 seconds. Other than `getProperty(String subdomain, String name)` seem to be not called from anywhere.

**Pull request merged**
