### PR TITLE
OF-1687: Introduce a new SystemProperty class

### PR DESCRIPTION
**Pull request by GregDThomas**
~~This is still a work in progress, but though I'd see if there was general support for this idea before I progressed further.~~

The idea is that a `SystemProperty` can represent the system properties currently accessed via `JiveGlobals`, stored in `ofProperty`. By providing a single place where they are referenced (the static method `SystemProperty.getProperties()`) it should be possible to incorporate their current/default values and description on the existing System Properties page. 

I'm not proposing to replace every access of JiveGlobals with this class, instead gradually migrate over time, and as more properties are migrated the System Properties page becomes more complete. 

Creating a sysprop can be done so;
```
        final SystemProperty<Long> property = SystemProperty.Builder.ofType(Long.class)
            .setKey("this-is-a-constrained-long-key")
            .setDefaultValue(42L)
            .setMinValue(0L)
            .setMaxValue(100L)
            .build();

        assertThat(longProperty.getValue(), is(42L));
        longProperty.setValue(84L);
        assertThat(longProperty.getValue(), is(84L));
```

See the tests for examples of how to use, but as it stands the properties can be a String, Integer, Long or Duration, with a default value, description, and optional min/max values. A listener can also be supplied, which will be called whenever the property changes.

### CODE REVIEW

**Comment by akrherz** [comment]
Hi @GregDThomas , thanks for undertaking this effort.  My main concern is how this change supports the auto-generation of documentation of all properties?  Or is the thought that the admin console would house the complete listing?

On the admin console, I would love UI that showed which settings are different than the default and which settings require a restart for application.

**Comment by GregDThomas** [comment]
OK, so this latest update adds a (read-only) UI. You can access it via http://localhost:9090/SystemProperties.jsp (slightly different URL, so the existing one can be left in place for now for comparison).

Example of this is as follows;
image

Is there general consensus that this a "Good Thing" (TM) and worth completing?

**Comment by akrherz** [comment]
@GregDThomas I certainly think it is a good thing.  Could there be an option to filter the listing to only show values that differ from their default?  The usage case is then an admin could know which options they have changed during the configuration of Openfire.

**Comment by GregDThomas** [comment]
The ‘Default Value’ drop down actually does this; the options are All/Changed/Unchanged/Unknown

**Comment by akrherz** [comment]
> The ‘Default Value’ drop down actually does this

Fancy, but my US two cents would be that this functionality should be for the 'Property Value' column, as you want to know if the property value differs from the default.

**Comment by GregDThomas** [comment]
Well, my thought process was along the lines of;
I can see a case (albeit contrived) where I may want to search by current value (e.g. 'which of the hybrid auth providers, primary, secondary or tertiary, is the DefaultAuthProvider). For that reason, I felt a free text box to search on current value for that column would be useful. I couldn't contrive an example where I may want to search by the default value, so use for that column for the 'it's changed from default' filter.

That said, I don't feel that strongly either way, so happy to change it if that's the general feeling. Would you propose that the 'default value' column is a free-text search instead?

**Comment by akrherz** [comment]
@GregDThomas Ah, I don't think I know much with regards to UI, so as long as the functionality is there, that works for me.

**Comment by GregDThomas** [comment]
OK, I think this may be more or less completed. OK, still need to actually define some more SystemProperty fields, but it's now possible to properly edit/encrypt/delete these new style properties in a sane manner.

**Comment by akrherz** [comment]
@GregDThomas What happens in the case of a single property being defined twice with different settings?  I am thinking of a property set in one class and then set again in another.

**Comment by GregDThomas** [comment]
A SystemProperty is guaranteed to have a unique key (an attempt to create a second property with the same key will cause an exception). The intent being that a property can only have one definition; typically a ‘public static final’ field member. 

However this does not stop code from getting/setting the same value via the existing JiveGlobals class which the SystemProperty essentially is a wrapper for.

**Comment by akrherz** [comment]
Thanks, I think I have exhausted my questions on this.  Is there a Jira issue associated for this change?

**Comment by GregDThomas** [comment]
No , no Jira currently. It kind of grew out of a thought experiment, I’ll raise a Jira and tidy up a few loose ends probably Friday, now.

**Comment by akrherz** [comment]
@GregDThomas I lied, I have another question.  What about i18n support for property descriptions?

**Comment by GregDThomas** [comment]
Hmm, a good point. Currently none, I’ll think about how to fold them in ...

**Comment by akrherz** [comment]
Thanks @GregDThomas , I think what you did for i18n is what I had in mind.

**Comment by GregDThomas** [comment]
I /think/ (famous last words) this is done now. I need to make some final checks, will squash all those commits down to one, and then see if people are still willing to merge it in ;)

**Comment by wrooot** [comment]
Don't forget the Jira ticket ;)

**Comment by GregDThomas** [comment]
There you go @guusdk ; list types can now be defined;

```
    private static final SystemProperty<List> ADMIN_JIDS = SystemProperty.Builder.ofType(List.class)
        .setCollectionType(String.class)
        .setKey("admin.authorizedJIDs")
        .setDefaultValue(Collections.emptyList())
        .setDynamic(true)
        .addListener(jids -> AdminManager.getInstance().refreshAdminAccounts())
        .build();
```

**Comment by GregDThomas** [comment]
OK, I think this does pretty much all it needs to. Lists, Sets, Enums, Classes, as well as a selection of basic types (String, Integer, Long, Boolean, JID, Duration, Instant). It's fairly easy to expand with new types (Collections and Enums probably being the hardest to implement!), so unless anyone objects in the next few days I plan to merge this in sometime next week.

**Comment by guusdk** [comment]
This is awesome, thanks @GregDThomas !

As discussed, we'll merge this in Master (to be included in 4.4.0), but not in the 4.3 branch.

**Pull request merged**
