### PR TITLE
OF-2256: Add CORS support to WebSocket Service

### PR DESCRIPTION
**Pull request by gjaekel**
In OpenMeetings (a part of Pàdé), one may switch form old-style BOSH to WebSockets for the XMPP controll connection.  but unlike the BOSH Service, the Websocket Service don't yet support CORS response headers.

Add this by using the code from https://github.com/igniterealtime/Openfire/blob/master/xmppserver/src/main/java/org/jivesoftware/openfire/http/HttpBindServlet.java

### CODE REVIEW

**Comment by gjaekel** [comment]
Does this patch make BOSH broken or is the failing connectivity test just a quick?

**Comment by guusdk** [comment]
@gjaekel I have rebased this PR, and made some modifications. Can you check if this still works for you?

**Comment by gjaekel** [comment]
Yes, it still "works for me™". 

I replaced the `openfire/lib/xmppserver-4.6.1.jar` by the ../xmppserver-4.7.0-SNAPSHOT` from a local build. With this I get still no CORS errors in the Console of an ongoing meeting session. And a manual fetch shows
```
gjaekel@celly:~$ wget -SO- 'https://eval.xmpp.dnb.de/ws/?room=bastelkeller'
--2021-05-20 11:44:44--  https://eval.xmpp.dnb.de/ws/?room=bastelkeller
Resolving eval.xmpp.dnb.de (eval.xmpp.dnb.de)... 193.175.100.141
Connecting to eval.xmpp.dnb.de (eval.xmpp.dnb.de)|193.175.100.141|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 405 Method Not Allowed
  Access-Control-Allow-Origin: *
  Access-Control-Allow-Methods: CANCELUPLOAD,HEAD,MKCOL,UNCHECKOUT,POST,CHECKIN,CHECKOUT,PROPFIND,LOCK,VERSION-CONTROL,COPY,REPORT,OPTIONS,PUT,DELETE,GETLIB,MOVE,GET,UPDATE,PROPPATCH,UNLOCK
  Access-Control-Allow-Headers: Destination,Overwrite,X-Requested-With,Cache-Control,X-File-Name,User-Agent,X-File-Size,If-Modified-Since,Depth,Content-Type
  Access-Control-Max-Age: 86400
  Cache-Control: must-revalidate,no-cache,no-store
  Content-Type: text/html;charset=iso-8859-1
  Content-Length: 528
2021-05-20 11:44:44 ERROR 405: Method Not Allowed.
```
in contrast to
```
gjaekel@celly:~$ wget -SO- 'https://xmpp.dnb.de/ws/?room=bastelkeller'
--2021-05-20 11:46:38--  https://xmpp.dnb.de/ws/?room=bastelkeller
Resolving xmpp.dnb.de (xmpp.dnb.de)... 193.175.100.146
Connecting to xmpp.dnb.de (xmpp.dnb.de)|193.175.100.146|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 405 Method Not Allowed
  Cache-Control: must-revalidate,no-cache,no-store
  Content-Type: text/html;charset=iso-8859-1
  Content-Length: 528
2021-05-20 11:46:38 ERROR 405: Method Not Allowed.
```
using `xmppserver-4.6.1.jar`, as on current Production.

**Comment by guusdk** [comment]
Are you happy for this to be merged then? Should we be concerned that the new build _also_ returns `HTTP/1.1 405 Method Not Allowed` in your test?

**Comment by guusdk** [comment]
Ok, thank you!

**Comment by guusdk** [comment]
Oh shoot, we should have a JIRA identifier for this.

**Pull request merged**
