### PR TITLE
OF-881: Simplify connection close semantics

### PR DESCRIPTION
**Pull request by tevans**
Avoid recursion and synchronization issues

### CODE REVIEW

**Comment by tevans** [comment]
Would like a review of this from @guusdk @sco0ter @dwd @akrherz before merge please.

**Comment by dwd** [comment]
Well... It *looks* right, but we went down a long path to get to the code @guus wrote that you're now removing. I wonder if later changes have removed the need for that as well?

Also, does it work (ie, have yo run a non-trivial deployment of this)?

**Comment by sco0ter** [comment]
Some random thoughts on this:
- I wonder if we could use a `AtomicReference<State> state` to get rid of the synchronized blocks, something like:
```java
                if (!state.compareAndSet(State.RUNNING, State.CLOSING)) {
                    return;
                }
```
- Having both `Session.STATUS_CLOSED` and `State.CLOSED` is confusing, isn't it?
- We should consider implementing `java.lang.AutoCloseable`... just because.
- The implemented behavior is called `idempotent` (closing a closed resource has no effect). Maybe it should be clear in the JavaDoc.
- It looks well otherwise. I think it works, `close()` should only run once, therfore no recursion, no deadlocks.

**Comment by guusdk** [comment]
Reduced complexity is good. I cannot see anything wrong with the change either (although I did not run tests - do we know how to get in touch with Andi? He used to be able to shake things down thoroughly). As for my original fix: It was the result of a trial-and-error session more than a solution that was well designed and executed. A good part of the problems that my changes tried to fix related to the issues that we had after upgrading MINA - which has since been rolled back.

**Comment by sco0ter** [comment]
@fowlerp I think you are right. `state = State.CLOSED;` is called outside the synchronization block as well. Read/Write access to class variables should always be synchronized on the *same* monitor, otherwise thread visibility issues may occur. Although it's surely hard to reproduce and proof here.
Alternatively the mentioned `AtomicReference` would help as well.

**Comment by tevans** [comment]
Ok - thanks all. I think we are agreed on the basic concept here, but I will make another update to incorporate some of this helpful feedback.

**Comment by tevans** [comment]
Review feedback applied. Note that we have done some initial testing to validate basic connection cases, but further testing (especially under load/concurrency scenarios) would be appreciated.

**Pull request merged**
