### PR TITLE
Fixed a mixor resource leak and updated some legacy html to use new tags

### PR DESCRIPTION
**Pull request by blackmambaza**

### CODE REVIEW

**Review by guusdk — APPROVED** [review]
Thanks for your contribution!

**Comment by guusdk** [comment]
I've been rebasing this PR to test a new change on the main branch, that should improve the stability of the continuous integration tests. This has precious little to do with the changes in this PR. I'm happy for this PR to be merged as-is.

**Comment by blackmambaza** [comment]
Nice one Guus! Let me know if I can help further. I love looking through legacy code as well if you need any help with clean ups.

**Comment by guusdk** [comment]
Thanks! We've got plenty of things for you to dig into. If you're into Openfire, then have a look at https://igniterealtime.atlassian.net/jira/software/c/projects/OF/issues

Alternatively, have a look at our Spark client. Anything you can contribute there would be most welcome too!

**Comment by guusdk** [comment]
Openfire, Spark and almost all plugins are basic Maven project, that should work with any applicable IDE. We're mostly using IntelliJ, but others should work as well. The [latest documentation that's bundled with Openfire](https://htmlpreview.github.io/?https://github.com/igniterealtime/Openfire/blob/main/documentation/index.html) has a tutorial of how to use VSCode, for example.

**Pull request merged**
