### PR TITLE
OF-1511 OF-1513 OF-1514: Pubsub / PEP changes

### PR DESCRIPTION
**Pull request by guusdk**
This PR includes a new feature, as well as a bugfixes.

### CODE REVIEW

**Comment by dwd** [comment]
What @sco0ter said - can we refactor the boolean checks to the form object? ("we" - heh)

**Comment by guusdk** [comment]
Something like this? I've copied the utility method that aught to go in Tinder to one of the classes here, marking it deprecated. That saves me from having to do a Tinder release just for this PR. I'll do that later, obviously.

**Comment by dwd** [comment]
Oh, Kay.

**Pull request merged**
