### PR TITLE
OF-874 disco#items request SHOULD return connected or available resources

### PR DESCRIPTION
**Pull request by sco0ter**

### CODE REVIEW

**Comment by dwd** [comment]
Shouldn't this only list resources for which the requester already has presence? Also, I'm interested as to what needs this, and which other servers implement it.

**Comment by sco0ter** [comment]
Not sure, what you mean with presence. It should behave like Example 15. in XEP-0030: Return all resources of the requesting user.
I saw this in ejabberd, too.

**Comment by sco0ter** [comment]
I now see what you mean. You are right, this probably needs some security check.

**Comment by Flowdalic** [comment]
I wonder if Openfire has a `boolean isSubscribedTo(Jid myJid, Jid otherJid)`. If not, then I think we should add such an method, because in XMPP there are just so many places where need to make decisions based on if an entity is subscribed to anthers entity presence.

**Comment by dwd** [comment]
It's more complicated than that. If I send directed presence to you, you should probably see that one even if you're not subscribed. It's basically the same logic, and function, as a probe, and probably dates from when probes weren't sent from end clients at all.

So there's a "canSeeSession" or something needed.

**Comment by sco0ter** [comment]
I've found the canProbePresence method for that. Unfortunately I don't know where and if Openfire has a "canSeeSession" for directed presence. Anybody an idea?

**Comment by dwd** [comment]
canProbePresence is enough, though it *should* also handle directed presence.

**Pull request merged**
