### PR TITLE
Use the version from the pom.xml to set the version in plugin.xml

### PR DESCRIPTION
**Pull request by GregDThomas**
During recent changes to various plugin.xml files for the plugins, it became clear that the plugin versions in plugin.xml did not necessarily match the plugin version in the pom.xml

Maven to the rescue - we already had the hooks in place to edit the pom.xml when the .jar file was created, it was simply a case of editing the plugin.xml appropriately. Now the plugin.xml and pom.xml have identical versions.

### CODE REVIEW

**Comment by guusdk** [comment]
Yup, I was meaning to do this after we dropped Ant support (but forgot). We can do something very similar for the name and description, by the way!

**Comment by GregDThomas** [comment]
Yes ... that probably makes sense!

**Comment by GregDThomas** [comment]
I did check; they are different. Which didn't concern me in the least, as the pom.xml names seemed more consistent with each other (.e.g `Callback on Offline Plugin` vs `CallbackOnOffline`). 

However, now you've raised it, I wonder if that's not such a good idea. I think the plugin names are used as keys, in the code, etc., so changing it is probably a big mistake. I suspect I should probably back that last change out.

**Comment by guusdk** [comment]
I have the same concern, but I'm not quite sure if it's valid. If memory
serves, it's the directory/jar file me that's used. I'm not completely sure
though. Perhaps it's better to retain the original names, just to be sure.

**Comment by GregDThomas** [comment]
Done; https://github.com/igniterealtime/Openfire/pull/1120

**Pull request merged**
