### PR TITLE
Denote Openfire 4.2.3 Release

### PR DESCRIPTION
**Pull request by akrherz**

### CODE REVIEW

**Comment by GregDThomas** [comment]
(again, the parents of otherwise unchanged plugins have changed ...)

**Comment by akrherz** [comment]
rebased and updated, anybody with thoughts other than the ongoing maven versioning :)

**Comment by guusdk** [comment]
Hurgh. I'm somewhat tempted to revert https://github.com/igniterealtime/Openfire/pull/1017 - which was a hackish fix that does not appear to solve the issue that it was attempting to solve - but reverting that would require additional fixes. I don't think it'd hurt to do a release with that change in it. I'm cautiously in favor of doing a release based on the code as-is.

**Comment by akrherz** [comment]
updated PR now and am smoke testing current 4.2 branch build on Ignite.  @dwd may we proceed?

**Pull request merged**
