### PR TITLE
OF-2876: Raise minimum Java version from 11 to 17

### PR DESCRIPTION
**Pull request by guusdk**
Openfire now requires Java 17 or later to run.

### CODE REVIEW

**Comment by guusdk** [comment]
cc: @stokito

**Comment by akrherz** [comment]
...due to an upcoming upgrade to Jetty requiring Java 17...

**Comment by guusdk** [comment]
Yeah, the Jetty upgrade is tracked in https://igniterealtime.atlassian.net/browse/OF-2717

**Comment by Fishbowler** [comment]
Why's Java 21 so unhappy?

**Comment by Fishbowler** [comment]
Found one you missed :wink:

**Comment by Fishbowler** [comment]
I have:
* built a docker container
* run Openfire
* logged into the admin console
* visited every page I can find
* installed the HTTP File Upload plugin

What I haven't done is anything XMPP related, because our automated suites will exercise that far more than I'm going to do.

**Comment by guusdk** [comment]
> Why's Java 21 so unhappy?

I believe that the test is using deprecated code that got removed from Java between 17 and 21. We should adjust our test implementation.

**Comment by guusdk** [comment]
There has been more talk of dubbing this 5.0.0 rather than 4.x. Why do you think there's a need for a intermediate release of 4.10?

**Comment by guusdk** [comment]
This PR has been rebased to be able to pull in the changes from https://github.com/igniterealtime/Openfire/pull/2592

**Pull request merged**
