### PR TITLE
Delete unused classes

### PR DESCRIPTION
**Pull request by sco0ter**
These classes are unused, can we delete them to get a cleaner code base?

### CODE REVIEW

**Comment by dwd** [comment]
Sounds reasonable to me.

**Comment by tevans** [comment]
FYI - I believe @guusdk was recently doing some work around SSLJiveTrustManager.java. Otherwise +1 from me.

**Comment by guusdk** [comment]
Although I'm deleting stuff myself, shouldn't we mark things as "deprecated" instead? That will give third party developers some leeway

**Comment by dwd** [comment]
I'm thinking these are things that if plugin developers are using, they're probably doing something wrong if Openfire isn't using them at all. So I'm merging and seeing what breaks...

**Pull request merged**
