### PR TITLE
Remove duplicated code

### PR DESCRIPTION
**Pull request by Alameyo**
Not functional changes, just refactor to use less code to do the same things. Perhaps I could work to reduce it a bit more.

### CODE REVIEW

**Comment by guusdk** [comment]
The same Smack integration test that is (occassionally) failing in this PR now causes an unrelated PR (#1721) to fail too. This makes it less likely that the cause is introduced by these PRs.

**Comment by guusdk** [comment]
A workaround has been merged to master, that should prevent this problem from causing problem. If you rebase your PR, it should go green.

**Comment by guusdk** [comment]
I just found out that I have the power to rebase this branch. I just attempted to do so. :)

**Comment by Alameyo** [comment]
Ok, so I guess it can be merged now or should I change anything else?

**Comment by guusdk** [comment]
Nope, this should be fine. Thanks!

**Pull request merged**
