### PR TITLE
OF-2405: Enhance log info of loaded plugin by version

### PR DESCRIPTION
**Pull request by gjaekel**
Add version info to the "Successfully loaded plugin"-message

### CODE REVIEW

**Review by guusdk — APPROVED** [review]

**Comment by guusdk** [comment]
Looks good. Thanks!

**Comment by gjaekel** [comment]
May you please check if this change looks good in the Openfire logfile? Or is there such a logfile available in the CI buildlogs?

**Comment by guusdk** [comment]
*gasp* you didn't test it? ;)

image

**Comment by gjaekel** [comment]
No, I can't in an easy way. But a syntax error had have break the build an a semantic error just disturb the log output. But I take a look at the sources and typical plugin.xml's what the content of this string would be. 

Thank you.

**Comment by guusdk** [comment]
Hah, I _did_ find a small issue: the admin console is loaded as a plugin, but has no version number. Upon start of the server, this is printed: 

```Successfully loaded plugin 'admin-null'.```

**Comment by gjaekel** [comment]
Hm, then you discovered a miss in the corresponding plugin.xml :smile:

**Comment by guusdk** [comment]
It doesn't have one. It's extraspecial! Let's just write a bit of code that ignores missing metadata or missing versions, to be safe.

**Comment by gjaekel** [comment]
> It doesn't have one. 

https://github.com/igniterealtime/Openfire/blob/master/xmppserver/plugin.xml seems to be copied to `.../plugins/admin/`

> a bit of code

`.toString().replace("null","<unknown>")`?

**Comment by guusdk** [comment]
I would just modify your original commit:

```java
if (metadata != null && metadata.getVersion != null) {
    Log.info( "Successfully loaded plugin '{}-{}'.", canonicalName, metadata.getVersion());
} else {
    Log.info( "Successfully loaded plugin '{}'.", canonicalName);
}

**Comment by gjaekel** [comment]
That look much more professional.

**Pull request merged**
