### PR TITLE
OF-2158 Update notifications should include cluster node reference

### PR DESCRIPTION
**Pull request by DJDANNY123**
Updates the updates notifications to include the hostname of the node which have plugins to be updated.

Tidies up an iterator in the same method

### CODE REVIEW

**Comment by Fishbowler** [comment]
Tested using https://github.com/surevine/openfire-docker-compose

image

Works on my machine :+1: 

Does the wording make sense in the context of a single server? i.e. Does "node" make sense outside of a cluster?

**Comment by akrherz** [comment]
> Does "node" make sense outside of a cluster?

I see your point, but think is isn't too confusing.  A "node" is the place of installation, in my mind.

**Comment by Fishbowler** [comment]
Took me a while, but got it tested on a standalone server. Tricky to get the UpdateManager to fire after the client connects. 
Future Us: Delete `update.lastCheck`, then stop/start the update service (Server Settings) then wait 30s.

**Comment by akrherz** [comment]
> Future Us: Delete `update.lastCheck`, then stop/start the update service (Server Settings) then wait 30s.

I thought http://localhost:9090/available-plugins.jsp, doom scroll to the bottom and then click 'Update Now' ?

**Comment by Fishbowler** [comment]
Aw man. That's sooo much easier :facepalm:

**Comment by guusdk** [comment]
> I see your point, but think is isn't too confusing. A "node" is the place of installation, in my mind.

It's not to confusing, but why add even a little? A simple if-statement to check if clustering is enabled could be used to conditionally add the hostname.

**Pull request merged**
