### PR TITLE
OF-1169 Allow java 7 or 8 as requirements for debian

### PR DESCRIPTION
**Pull request by akrherz**
completely untested by me, will attempt to find folks to comment on this.

### CODE REVIEW

**Comment by akrherz** [comment]
OK, thanks to @dwd hint, I think I have this PR straightened out

**Comment by dwd** [comment]
Looks good to me.

**Comment by Whissi** [comment]
This has broken my Debian Jessie setup: Since v3.10 I was using Oracle JRE created by myself using Debian's `make-jpkg` tool. But now only "default-jre-headless" satisfy your requirement... please depend on `default-jre-headless | oracle-java7-jre`.

**Comment by akrherz** [comment]
@Whissi Thanks for your feedback.  Can't you install default-jre-headless to satisfy the requirement and just edit /etc/default/openfire or use alternatives to set your default java?

**Comment by Whissi** [comment]
If I would install `default-jre-headless` I would pull-in the following packages:
```
# apt-get install default-jre-headless
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  ca-certificates-java java-common libpcsclite1 libsctp1 lksctp-tools openjdk-7-jre-headless tzdata-java
Suggested packages:
  default-jre pcscd icedtea-7-jre-jamvm libnss-mdns sun-java6-fonts fonts-dejavu-extra fonts-ipafont-gothic fonts-ipafont-mincho ttf-wqy-microhei ttf-wqy-zenhei fonts-indic
The following NEW packages will be installed:
  ca-certificates-java default-jre-headless java-common libpcsclite1 libsctp1 lksctp-tools openjdk-7-jre-headless tzdata-java
0 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
Need to get 39,8 MB of archives.
```
...something I don't really need and therefore don't want.

**Comment by akrherz** [comment]
can you describe how the package `oracle-java7-jre` is standardized within Ubuntu / Debian?

**Comment by Whissi** [comment]
Sorry, I am not a Debian guy. All I can tell you is that I am using https://wiki.debian.org/JavaPackage to create my own JRE package for Oracle releases. Packages created by that script will have set `Provide` like
```
Provides: java-browser-plugin, java-runtime, java-runtime-headless, java-virtual-machine, java2-runtime, java2-runtime-headless, java6-runtime, java6-runtime-headless, java7-runtime, java7-runtime-headless, java8-runtime, java8-runtime-headless
```
So maybe you should set `default-jre-headless | java7-runtime-headles` which will target other JRE (and JDK) implementation as well and isn't too Oracle-specific?

**Pull request merged**
