### PR TITLE
OF-1837: JDBC Providers: allow JIDs to be (un)escaped

### PR DESCRIPTION
**Pull request by guusdk**

### CODE REVIEW

**Comment by guusdk** [comment]
This commit adds new configuration options, but leaves the default behavior intact.

I'm considering toggling the default, as I suspect that it will help a lot of people that are now unaware of encoding issues. It can, however, cause issues for people that already have encoding in place, in their database. I'm not sure what outweighs what here.

**Comment by guusdk** [comment]
FWIW, we've tested a backported version of this change on wikisuite.chat, that had a user with a space in the username. The change seems to prevent many stacktraces in the log files.

**Comment by guusdk** [comment]
Auch - why is this failing in Travis, but not for me locally?

**Comment by mnsuccess** [comment]
> Auch - why is this failing in Travis, but not for me locally?

failing on the test JDBCAuthProviderTest !! maybe something  wrong with encryption of the password according to the PasswordTypes of JDBCAuthProvider

**Comment by guusdk** [comment]
> failing on the test JDBCAuthProviderTest !! maybe something wrong with encryption of the password according to the PasswordTypes of JDBCAuthProvider

Maybe - but it's strange that when I run the same tests at my computer, they all pass without problem. Can you reproduce the test failures on your computer?

**Comment by GregDThomas** [comment]
What char encoding are you using on your computer?
What char encoding are you using Travis?

**Comment by mnsuccess** [comment]
> > failing on the test JDBCAuthProviderTest !! maybe something wrong with encryption of the password according to the PasswordTypes of JDBCAuthProvider
> 
> Maybe - but it's strange that when I run the same tests at my computer, they all pass without problem. Can you reproduce the test failures on your computer?

okay !! Let me test

**Comment by mnsuccess** [comment]
> > failing on the test JDBCAuthProviderTest !! maybe something wrong with encryption of the password according to the PasswordTypes of JDBCAuthProvider
> 
> Maybe - but it's strange that when I run the same tests at my computer, they all pass without problem. Can you reproduce the test failures on your computer?

strange the test does not fail when I built the source code with **mvn verify** and it fails when I run it directly ( failed 5)

**Comment by guusdk** [comment]
I'm absolutely lost here.

**Comment by guusdk** [comment]
I've rebased this PR just now.

**Comment by akrherz** [comment]
The Travis-CI failures here look germane to the PR...

**Comment by guusdk** [comment]
I agree - but I'm having trouble finding the cause. It is frustratingly error free on my local machine.

@GregDThomas help!

**Comment by guusdk** [comment]
I've rebased this PR just now.

**Comment by guusdk** [comment]
In an attempt to isolate the problem, I've replaced this on PR with three PRs, that each add one of the commits that were combined here.

These are the new PRs:
- #1643
- #1644 
- #1645

**Pull request closed without merging**
