### PR TITLE
OF-1932: Ensure we use the correct password when running tests

### PR DESCRIPTION
**Pull request by GregDThomas**

### CODE REVIEW

**Comment by GregDThomas** [comment]
Possibly a candidate for the 4.4 branch as this was introduced by https://issues.igniterealtime.org/browse/OF-1873

**Comment by guusdk** [comment]
`computeIfAbsent` will not only return the 'if absent' value, but will also add that value to the map. Is that what is desired in this case?

**Comment by GregDThomas** [comment]
Not sure at this point. Just copied the line you had used elsewhere. Will ponder the matter further ...

**Comment by GregDThomas** [comment]
> `computeIfAbsent` will not only return the 'if absent' value, but will also add that value to the map. Is that what is desired in this case?

Yes, that is what is intended. The (existing) password needs to be in the settings being passed to the temporary LdapManager used to test the user/group so the test has a chance of passing.

**Comment by guusdk** [comment]
Once again: thank you!

**Pull request merged**
