### PR TITLE
ofmeet plugin version 0.3.1

### PR DESCRIPTION
**Pull request by deleolajide**
Fixed issue with broken presence broadcast
Fixed issue with broken desktop/screen sharing
Fixed issue with missing jnsctp.dll dependencies
Removed some more redundant or duplicate jar files in jitsivideobridge lib

### CODE REVIEW

**Comment by akrherz** [comment]
Hi @deleolajide , do you think these changes could be picked back onto the 3.10 branch of ofmeet? Otherwise, we can't really place this version on the website for download at the moment :(

**Comment by deleolajide** [comment]
These changes were to fix a combination of issues from OF 4.0 changes and Chrome browser changes. I can back port the Chrome browser changes to 3.10 branch and create a pull request against it.

**Comment by deleolajide** [comment]
@akrherz , the 3.10 branch has a very old version (0.1.4). I had limited time to fix the issues against the head of code tree. I am happy to wait for a general release on the web site with ofmeet 0.3.x when OF 4.0 is released.

**Comment by akrherz** [comment]
@deleolajide , yeah, I should have looked more closely at it.  Thanks for your patience.

**Pull request merged**
