### PR TITLE
OF-1506: Encrypt database and LDAP settings created during set-up

### PR DESCRIPTION
**Pull request by GregDThomas**
Note; whilst I've confirmed that this PR ensures that the database credentials are properly encrypted, I've not been able to test the LDAP settings, I hope it's working OK but someone else should probably test it too.

### CODE REVIEW

**Comment by akrherz** [comment]
Getting LDAP testing for Openfire is tasked for @speedy01  :)  Will merge this and ping him prior to release of 4.3.0 for testing

**Comment by speedy01** [comment]
I'll run through a fresh install tomorrow and let you know. side note: it looks like my ldap creds are already encrypted..

**Comment by GregDThomas** [comment]
OK, clearly this needs more work. I'll revisit it today.

**Comment by speedy01** [comment]
I'm installing from the nightly build and against a fresh DB.  I'll try again!

**Comment by speedy01** [comment]
@GregDThomas sorry to report that it did not encrypt again on a ms sql db.  I haven't tested against anything else though...

**Comment by GregDThomas** [comment]
OK, thanks. I'll have to run up a MySQL DB to see how that changes things.

**Comment by akrherz** [comment]
@speedy01 from where did you get the current nightly of openfire?

**Comment by speedy01** [comment]
that might be my problem.  it looks like I have grabbed an old version without realizing it.  I'll grab from bamboo shortly and try again!

**Comment by akrherz** [comment]
@speedy01 my bad, I have now fixed the [website nightlies](http://www.igniterealtime.org/downloads/nightly_openfire.jsp)

**Pull request merged**
