### PR TITLE
Audit manager property listener

### PR DESCRIPTION
**Pull request by trumpetx**
See https://community.igniterealtime.org/message/253414#253414 for reported bug

### CODE REVIEW

**Comment by akrherz** [comment]
Thanks for your contribution, but you are mixing a number of code changes into one PR.  Please isolate this property listener change into one commit.

**Comment by trumpetx** [comment]
One commit has changes, the other is all formatting.  I'll rebase and resubmit per your request.

**Comment by akrherz** [comment]
@trumpetx Your first commit has an unrelated change to `build.xml`

**Comment by trumpetx** [comment]
Oh, I though you were referring to the multiple commits.  The informational addition to the build.xml script didn't seem enough to warrant a separate pull request.  I'll just pull it out.  You guys can add in the extra information if you deem necessary.

**Comment by trumpetx** [comment]
I would like to test one more thing before I resubmit (I just remembered I left work before confirming something).  I'll resubmit in the morning.  Thanks.

**Comment by trumpetx** [comment]
Resubmitted: https://github.com/igniterealtime/Openfire/pull/382

**Pull request closed without merging**
