### PR TITLE
OF-1422 Check all MUCRoles, handle nickname changes

### PR DESCRIPTION
**Pull request by dwd**
This fixes various errors found during examination of the source, including:

* Check all MUCRoles for nickname rejoining.
* Check for nickname sharing for nickname changes and reject.
* Handle Presence errors and similar.

### CODE REVIEW

**Comment by akrherz** [comment]
Where's the subsequent "I hate CRLF" commit? :)

**Comment by dwd** [comment]
Oh, for the ache of Fux. I'll sort that in a minute.

**Comment by akrherz** [comment]
Seems reasonable to me, interesting that the MUC ignore error packets has been around for 10 years, it seems.  I thought this was a more recent change than that.

**Comment by akrherz** [comment]
Sorry for the arbitrary comment on this PR, trying to get our Jira synced on the status of this PR :(

**Pull request merged**
