### PR TITLE
OF-2620: Use Openfire assets on Plugin pages

### PR DESCRIPTION
**Pull request by Fishbowler**
… rather than force them to duplicate

There's only one of these that I can find. And it's a 1 character change.

### CODE REVIEW

**Comment by guusdk** [comment]
It used to be possible to have the admin console be exposed on a URL that is not the context root of the domain (eg: `https://example.org/internal/` using URL rewriting magic). Although I'm not sure if that's even possible anymore, the change in this PR would most definately break it. Is there another way that we can achieve this, without turning the URL into something that's absolute rather than relative?

**Comment by Fishbowler** [comment]
I haven't found a way through code or config to expose it on another URL, but I assume you could expose it via a reverse proxy.
A quick search of the codebase shows that there aren't any links that would be broken by that, but there are a few images. This would make 8, but one of the existing ones is the logo on the main page.

There's some server-side hackery to say "from the root, even if that's a directory", but that wouldn't help a reverse proxy.

I could put a safe number of instances of  `../` before the image reference to ensure it's getting to the root, but that's _more_ likely to break a reverse proxy.

I think the right solution is to rely on a reverse proxy being correctly configured for URL rewriting.

**Comment by Fishbowler** [comment]
This now:
* shows info images in an infobox on plugin pages
* removes some console errors on plugin pages about not finding CSS

**Comment by guusdk** [comment]
Ohh, what's this?

image

**Comment by Fishbowler** [comment]
Rebased.

**Comment by Fishbowler** [comment]
Fixed the path, but can't be tested until we fix OF-2668

**Comment by guusdk** [comment]
Given that someone else just posted the exact same fix, I'm confident enough that this does more good than harm. I'm merging as-is.

**Pull request merged**
